// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package logger_mock

//go:generate minimock -i ed_in_memory_database/internal/pkg/mocks/logger_mock.loggerAlias -o core_logger.mock.gen.go -n LoggerAliasMock -p logger_mock

import (
	"ed_in_memory_database/pkg/logger"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LoggerAliasMock implements loggerAlias
type LoggerAliasMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDebugf          func(message string, args ...any)
	funcDebugfOrigin    string
	inspectFuncDebugf   func(message string, args ...any)
	afterDebugfCounter  uint64
	beforeDebugfCounter uint64
	DebugfMock          mLoggerAliasMockDebugf

	funcErrorf          func(message string, args ...any)
	funcErrorfOrigin    string
	inspectFuncErrorf   func(message string, args ...any)
	afterErrorfCounter  uint64
	beforeErrorfCounter uint64
	ErrorfMock          mLoggerAliasMockErrorf

	funcFatalf          func(message string, args ...any)
	funcFatalfOrigin    string
	inspectFuncFatalf   func(message string, args ...any)
	afterFatalfCounter  uint64
	beforeFatalfCounter uint64
	FatalfMock          mLoggerAliasMockFatalf

	funcInfof          func(message string, args ...any)
	funcInfofOrigin    string
	inspectFuncInfof   func(message string, args ...any)
	afterInfofCounter  uint64
	beforeInfofCounter uint64
	InfofMock          mLoggerAliasMockInfof

	funcSync          func() (err error)
	funcSyncOrigin    string
	inspectFuncSync   func()
	afterSyncCounter  uint64
	beforeSyncCounter uint64
	SyncMock          mLoggerAliasMockSync

	funcWarnf          func(message string, args ...any)
	funcWarnfOrigin    string
	inspectFuncWarnf   func(message string, args ...any)
	afterWarnfCounter  uint64
	beforeWarnfCounter uint64
	WarnfMock          mLoggerAliasMockWarnf

	funcWithf          func(key logger.Field, value any) (l1 logger.Logger)
	funcWithfOrigin    string
	inspectFuncWithf   func(key logger.Field, value any)
	afterWithfCounter  uint64
	beforeWithfCounter uint64
	WithfMock          mLoggerAliasMockWithf
}

// NewLoggerAliasMock returns a mock for loggerAlias
func NewLoggerAliasMock(t minimock.Tester) *LoggerAliasMock {
	m := &LoggerAliasMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DebugfMock = mLoggerAliasMockDebugf{mock: m}
	m.DebugfMock.callArgs = []*LoggerAliasMockDebugfParams{}

	m.ErrorfMock = mLoggerAliasMockErrorf{mock: m}
	m.ErrorfMock.callArgs = []*LoggerAliasMockErrorfParams{}

	m.FatalfMock = mLoggerAliasMockFatalf{mock: m}
	m.FatalfMock.callArgs = []*LoggerAliasMockFatalfParams{}

	m.InfofMock = mLoggerAliasMockInfof{mock: m}
	m.InfofMock.callArgs = []*LoggerAliasMockInfofParams{}

	m.SyncMock = mLoggerAliasMockSync{mock: m}

	m.WarnfMock = mLoggerAliasMockWarnf{mock: m}
	m.WarnfMock.callArgs = []*LoggerAliasMockWarnfParams{}

	m.WithfMock = mLoggerAliasMockWithf{mock: m}
	m.WithfMock.callArgs = []*LoggerAliasMockWithfParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLoggerAliasMockDebugf struct {
	optional           bool
	mock               *LoggerAliasMock
	defaultExpectation *LoggerAliasMockDebugfExpectation
	expectations       []*LoggerAliasMockDebugfExpectation

	callArgs []*LoggerAliasMockDebugfParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LoggerAliasMockDebugfExpectation specifies expectation struct of the loggerAlias.Debugf
type LoggerAliasMockDebugfExpectation struct {
	mock               *LoggerAliasMock
	params             *LoggerAliasMockDebugfParams
	paramPtrs          *LoggerAliasMockDebugfParamPtrs
	expectationOrigins LoggerAliasMockDebugfExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// LoggerAliasMockDebugfParams contains parameters of the loggerAlias.Debugf
type LoggerAliasMockDebugfParams struct {
	message string
	args    []any
}

// LoggerAliasMockDebugfParamPtrs contains pointers to parameters of the loggerAlias.Debugf
type LoggerAliasMockDebugfParamPtrs struct {
	message *string
	args    *[]any
}

// LoggerAliasMockDebugfOrigins contains origins of expectations of the loggerAlias.Debugf
type LoggerAliasMockDebugfExpectationOrigins struct {
	origin        string
	originMessage string
	originArgs    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDebugf *mLoggerAliasMockDebugf) Optional() *mLoggerAliasMockDebugf {
	mmDebugf.optional = true
	return mmDebugf
}

// Expect sets up expected params for loggerAlias.Debugf
func (mmDebugf *mLoggerAliasMockDebugf) Expect(message string, args ...any) *mLoggerAliasMockDebugf {
	if mmDebugf.mock.funcDebugf != nil {
		mmDebugf.mock.t.Fatalf("LoggerAliasMock.Debugf mock is already set by Set")
	}

	if mmDebugf.defaultExpectation == nil {
		mmDebugf.defaultExpectation = &LoggerAliasMockDebugfExpectation{}
	}

	if mmDebugf.defaultExpectation.paramPtrs != nil {
		mmDebugf.mock.t.Fatalf("LoggerAliasMock.Debugf mock is already set by ExpectParams functions")
	}

	mmDebugf.defaultExpectation.params = &LoggerAliasMockDebugfParams{message, args}
	mmDebugf.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDebugf.expectations {
		if minimock.Equal(e.params, mmDebugf.defaultExpectation.params) {
			mmDebugf.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDebugf.defaultExpectation.params)
		}
	}

	return mmDebugf
}

// ExpectMessageParam1 sets up expected param message for loggerAlias.Debugf
func (mmDebugf *mLoggerAliasMockDebugf) ExpectMessageParam1(message string) *mLoggerAliasMockDebugf {
	if mmDebugf.mock.funcDebugf != nil {
		mmDebugf.mock.t.Fatalf("LoggerAliasMock.Debugf mock is already set by Set")
	}

	if mmDebugf.defaultExpectation == nil {
		mmDebugf.defaultExpectation = &LoggerAliasMockDebugfExpectation{}
	}

	if mmDebugf.defaultExpectation.params != nil {
		mmDebugf.mock.t.Fatalf("LoggerAliasMock.Debugf mock is already set by Expect")
	}

	if mmDebugf.defaultExpectation.paramPtrs == nil {
		mmDebugf.defaultExpectation.paramPtrs = &LoggerAliasMockDebugfParamPtrs{}
	}
	mmDebugf.defaultExpectation.paramPtrs.message = &message
	mmDebugf.defaultExpectation.expectationOrigins.originMessage = minimock.CallerInfo(1)

	return mmDebugf
}

// ExpectArgsParam2 sets up expected param args for loggerAlias.Debugf
func (mmDebugf *mLoggerAliasMockDebugf) ExpectArgsParam2(args ...any) *mLoggerAliasMockDebugf {
	if mmDebugf.mock.funcDebugf != nil {
		mmDebugf.mock.t.Fatalf("LoggerAliasMock.Debugf mock is already set by Set")
	}

	if mmDebugf.defaultExpectation == nil {
		mmDebugf.defaultExpectation = &LoggerAliasMockDebugfExpectation{}
	}

	if mmDebugf.defaultExpectation.params != nil {
		mmDebugf.mock.t.Fatalf("LoggerAliasMock.Debugf mock is already set by Expect")
	}

	if mmDebugf.defaultExpectation.paramPtrs == nil {
		mmDebugf.defaultExpectation.paramPtrs = &LoggerAliasMockDebugfParamPtrs{}
	}
	mmDebugf.defaultExpectation.paramPtrs.args = &args
	mmDebugf.defaultExpectation.expectationOrigins.originArgs = minimock.CallerInfo(1)

	return mmDebugf
}

// Inspect accepts an inspector function that has same arguments as the loggerAlias.Debugf
func (mmDebugf *mLoggerAliasMockDebugf) Inspect(f func(message string, args ...any)) *mLoggerAliasMockDebugf {
	if mmDebugf.mock.inspectFuncDebugf != nil {
		mmDebugf.mock.t.Fatalf("Inspect function is already set for LoggerAliasMock.Debugf")
	}

	mmDebugf.mock.inspectFuncDebugf = f

	return mmDebugf
}

// Return sets up results that will be returned by loggerAlias.Debugf
func (mmDebugf *mLoggerAliasMockDebugf) Return() *LoggerAliasMock {
	if mmDebugf.mock.funcDebugf != nil {
		mmDebugf.mock.t.Fatalf("LoggerAliasMock.Debugf mock is already set by Set")
	}

	if mmDebugf.defaultExpectation == nil {
		mmDebugf.defaultExpectation = &LoggerAliasMockDebugfExpectation{mock: mmDebugf.mock}
	}

	mmDebugf.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDebugf.mock
}

// Set uses given function f to mock the loggerAlias.Debugf method
func (mmDebugf *mLoggerAliasMockDebugf) Set(f func(message string, args ...any)) *LoggerAliasMock {
	if mmDebugf.defaultExpectation != nil {
		mmDebugf.mock.t.Fatalf("Default expectation is already set for the loggerAlias.Debugf method")
	}

	if len(mmDebugf.expectations) > 0 {
		mmDebugf.mock.t.Fatalf("Some expectations are already set for the loggerAlias.Debugf method")
	}

	mmDebugf.mock.funcDebugf = f
	mmDebugf.mock.funcDebugfOrigin = minimock.CallerInfo(1)
	return mmDebugf.mock
}

// When sets expectation for the loggerAlias.Debugf which will trigger the result defined by the following
// Then helper
func (mmDebugf *mLoggerAliasMockDebugf) When(message string, args ...any) *LoggerAliasMockDebugfExpectation {
	if mmDebugf.mock.funcDebugf != nil {
		mmDebugf.mock.t.Fatalf("LoggerAliasMock.Debugf mock is already set by Set")
	}

	expectation := &LoggerAliasMockDebugfExpectation{
		mock:               mmDebugf.mock,
		params:             &LoggerAliasMockDebugfParams{message, args},
		expectationOrigins: LoggerAliasMockDebugfExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDebugf.expectations = append(mmDebugf.expectations, expectation)
	return expectation
}

// Then sets up loggerAlias.Debugf return parameters for the expectation previously defined by the When method

func (e *LoggerAliasMockDebugfExpectation) Then() *LoggerAliasMock {
	return e.mock
}

// Times sets number of times loggerAlias.Debugf should be invoked
func (mmDebugf *mLoggerAliasMockDebugf) Times(n uint64) *mLoggerAliasMockDebugf {
	if n == 0 {
		mmDebugf.mock.t.Fatalf("Times of LoggerAliasMock.Debugf mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDebugf.expectedInvocations, n)
	mmDebugf.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDebugf
}

func (mmDebugf *mLoggerAliasMockDebugf) invocationsDone() bool {
	if len(mmDebugf.expectations) == 0 && mmDebugf.defaultExpectation == nil && mmDebugf.mock.funcDebugf == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDebugf.mock.afterDebugfCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDebugf.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Debugf implements loggerAlias
func (mmDebugf *LoggerAliasMock) Debugf(message string, args ...any) {
	mm_atomic.AddUint64(&mmDebugf.beforeDebugfCounter, 1)
	defer mm_atomic.AddUint64(&mmDebugf.afterDebugfCounter, 1)

	mmDebugf.t.Helper()

	if mmDebugf.inspectFuncDebugf != nil {
		mmDebugf.inspectFuncDebugf(message, args...)
	}

	mm_params := LoggerAliasMockDebugfParams{message, args}

	// Record call args
	mmDebugf.DebugfMock.mutex.Lock()
	mmDebugf.DebugfMock.callArgs = append(mmDebugf.DebugfMock.callArgs, &mm_params)
	mmDebugf.DebugfMock.mutex.Unlock()

	for _, e := range mmDebugf.DebugfMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmDebugf.DebugfMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDebugf.DebugfMock.defaultExpectation.Counter, 1)
		mm_want := mmDebugf.DebugfMock.defaultExpectation.params
		mm_want_ptrs := mmDebugf.DebugfMock.defaultExpectation.paramPtrs

		mm_got := LoggerAliasMockDebugfParams{message, args}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.message != nil && !minimock.Equal(*mm_want_ptrs.message, mm_got.message) {
				mmDebugf.t.Errorf("LoggerAliasMock.Debugf got unexpected parameter message, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDebugf.DebugfMock.defaultExpectation.expectationOrigins.originMessage, *mm_want_ptrs.message, mm_got.message, minimock.Diff(*mm_want_ptrs.message, mm_got.message))
			}

			if mm_want_ptrs.args != nil && !minimock.Equal(*mm_want_ptrs.args, mm_got.args) {
				mmDebugf.t.Errorf("LoggerAliasMock.Debugf got unexpected parameter args, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDebugf.DebugfMock.defaultExpectation.expectationOrigins.originArgs, *mm_want_ptrs.args, mm_got.args, minimock.Diff(*mm_want_ptrs.args, mm_got.args))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDebugf.t.Errorf("LoggerAliasMock.Debugf got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDebugf.DebugfMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmDebugf.funcDebugf != nil {
		mmDebugf.funcDebugf(message, args...)
		return
	}
	mmDebugf.t.Fatalf("Unexpected call to LoggerAliasMock.Debugf. %v %v", message, args)

}

// DebugfAfterCounter returns a count of finished LoggerAliasMock.Debugf invocations
func (mmDebugf *LoggerAliasMock) DebugfAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDebugf.afterDebugfCounter)
}

// DebugfBeforeCounter returns a count of LoggerAliasMock.Debugf invocations
func (mmDebugf *LoggerAliasMock) DebugfBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDebugf.beforeDebugfCounter)
}

// Calls returns a list of arguments used in each call to LoggerAliasMock.Debugf.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDebugf *mLoggerAliasMockDebugf) Calls() []*LoggerAliasMockDebugfParams {
	mmDebugf.mutex.RLock()

	argCopy := make([]*LoggerAliasMockDebugfParams, len(mmDebugf.callArgs))
	copy(argCopy, mmDebugf.callArgs)

	mmDebugf.mutex.RUnlock()

	return argCopy
}

// MinimockDebugfDone returns true if the count of the Debugf invocations corresponds
// the number of defined expectations
func (m *LoggerAliasMock) MinimockDebugfDone() bool {
	if m.DebugfMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DebugfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DebugfMock.invocationsDone()
}

// MinimockDebugfInspect logs each unmet expectation
func (m *LoggerAliasMock) MinimockDebugfInspect() {
	for _, e := range m.DebugfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LoggerAliasMock.Debugf at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDebugfCounter := mm_atomic.LoadUint64(&m.afterDebugfCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DebugfMock.defaultExpectation != nil && afterDebugfCounter < 1 {
		if m.DebugfMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LoggerAliasMock.Debugf at\n%s", m.DebugfMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LoggerAliasMock.Debugf at\n%s with params: %#v", m.DebugfMock.defaultExpectation.expectationOrigins.origin, *m.DebugfMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDebugf != nil && afterDebugfCounter < 1 {
		m.t.Errorf("Expected call to LoggerAliasMock.Debugf at\n%s", m.funcDebugfOrigin)
	}

	if !m.DebugfMock.invocationsDone() && afterDebugfCounter > 0 {
		m.t.Errorf("Expected %d calls to LoggerAliasMock.Debugf at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DebugfMock.expectedInvocations), m.DebugfMock.expectedInvocationsOrigin, afterDebugfCounter)
	}
}

type mLoggerAliasMockErrorf struct {
	optional           bool
	mock               *LoggerAliasMock
	defaultExpectation *LoggerAliasMockErrorfExpectation
	expectations       []*LoggerAliasMockErrorfExpectation

	callArgs []*LoggerAliasMockErrorfParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LoggerAliasMockErrorfExpectation specifies expectation struct of the loggerAlias.Errorf
type LoggerAliasMockErrorfExpectation struct {
	mock               *LoggerAliasMock
	params             *LoggerAliasMockErrorfParams
	paramPtrs          *LoggerAliasMockErrorfParamPtrs
	expectationOrigins LoggerAliasMockErrorfExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// LoggerAliasMockErrorfParams contains parameters of the loggerAlias.Errorf
type LoggerAliasMockErrorfParams struct {
	message string
	args    []any
}

// LoggerAliasMockErrorfParamPtrs contains pointers to parameters of the loggerAlias.Errorf
type LoggerAliasMockErrorfParamPtrs struct {
	message *string
	args    *[]any
}

// LoggerAliasMockErrorfOrigins contains origins of expectations of the loggerAlias.Errorf
type LoggerAliasMockErrorfExpectationOrigins struct {
	origin        string
	originMessage string
	originArgs    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmErrorf *mLoggerAliasMockErrorf) Optional() *mLoggerAliasMockErrorf {
	mmErrorf.optional = true
	return mmErrorf
}

// Expect sets up expected params for loggerAlias.Errorf
func (mmErrorf *mLoggerAliasMockErrorf) Expect(message string, args ...any) *mLoggerAliasMockErrorf {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("LoggerAliasMock.Errorf mock is already set by Set")
	}

	if mmErrorf.defaultExpectation == nil {
		mmErrorf.defaultExpectation = &LoggerAliasMockErrorfExpectation{}
	}

	if mmErrorf.defaultExpectation.paramPtrs != nil {
		mmErrorf.mock.t.Fatalf("LoggerAliasMock.Errorf mock is already set by ExpectParams functions")
	}

	mmErrorf.defaultExpectation.params = &LoggerAliasMockErrorfParams{message, args}
	mmErrorf.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmErrorf.expectations {
		if minimock.Equal(e.params, mmErrorf.defaultExpectation.params) {
			mmErrorf.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmErrorf.defaultExpectation.params)
		}
	}

	return mmErrorf
}

// ExpectMessageParam1 sets up expected param message for loggerAlias.Errorf
func (mmErrorf *mLoggerAliasMockErrorf) ExpectMessageParam1(message string) *mLoggerAliasMockErrorf {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("LoggerAliasMock.Errorf mock is already set by Set")
	}

	if mmErrorf.defaultExpectation == nil {
		mmErrorf.defaultExpectation = &LoggerAliasMockErrorfExpectation{}
	}

	if mmErrorf.defaultExpectation.params != nil {
		mmErrorf.mock.t.Fatalf("LoggerAliasMock.Errorf mock is already set by Expect")
	}

	if mmErrorf.defaultExpectation.paramPtrs == nil {
		mmErrorf.defaultExpectation.paramPtrs = &LoggerAliasMockErrorfParamPtrs{}
	}
	mmErrorf.defaultExpectation.paramPtrs.message = &message
	mmErrorf.defaultExpectation.expectationOrigins.originMessage = minimock.CallerInfo(1)

	return mmErrorf
}

// ExpectArgsParam2 sets up expected param args for loggerAlias.Errorf
func (mmErrorf *mLoggerAliasMockErrorf) ExpectArgsParam2(args ...any) *mLoggerAliasMockErrorf {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("LoggerAliasMock.Errorf mock is already set by Set")
	}

	if mmErrorf.defaultExpectation == nil {
		mmErrorf.defaultExpectation = &LoggerAliasMockErrorfExpectation{}
	}

	if mmErrorf.defaultExpectation.params != nil {
		mmErrorf.mock.t.Fatalf("LoggerAliasMock.Errorf mock is already set by Expect")
	}

	if mmErrorf.defaultExpectation.paramPtrs == nil {
		mmErrorf.defaultExpectation.paramPtrs = &LoggerAliasMockErrorfParamPtrs{}
	}
	mmErrorf.defaultExpectation.paramPtrs.args = &args
	mmErrorf.defaultExpectation.expectationOrigins.originArgs = minimock.CallerInfo(1)

	return mmErrorf
}

// Inspect accepts an inspector function that has same arguments as the loggerAlias.Errorf
func (mmErrorf *mLoggerAliasMockErrorf) Inspect(f func(message string, args ...any)) *mLoggerAliasMockErrorf {
	if mmErrorf.mock.inspectFuncErrorf != nil {
		mmErrorf.mock.t.Fatalf("Inspect function is already set for LoggerAliasMock.Errorf")
	}

	mmErrorf.mock.inspectFuncErrorf = f

	return mmErrorf
}

// Return sets up results that will be returned by loggerAlias.Errorf
func (mmErrorf *mLoggerAliasMockErrorf) Return() *LoggerAliasMock {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("LoggerAliasMock.Errorf mock is already set by Set")
	}

	if mmErrorf.defaultExpectation == nil {
		mmErrorf.defaultExpectation = &LoggerAliasMockErrorfExpectation{mock: mmErrorf.mock}
	}

	mmErrorf.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmErrorf.mock
}

// Set uses given function f to mock the loggerAlias.Errorf method
func (mmErrorf *mLoggerAliasMockErrorf) Set(f func(message string, args ...any)) *LoggerAliasMock {
	if mmErrorf.defaultExpectation != nil {
		mmErrorf.mock.t.Fatalf("Default expectation is already set for the loggerAlias.Errorf method")
	}

	if len(mmErrorf.expectations) > 0 {
		mmErrorf.mock.t.Fatalf("Some expectations are already set for the loggerAlias.Errorf method")
	}

	mmErrorf.mock.funcErrorf = f
	mmErrorf.mock.funcErrorfOrigin = minimock.CallerInfo(1)
	return mmErrorf.mock
}

// When sets expectation for the loggerAlias.Errorf which will trigger the result defined by the following
// Then helper
func (mmErrorf *mLoggerAliasMockErrorf) When(message string, args ...any) *LoggerAliasMockErrorfExpectation {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("LoggerAliasMock.Errorf mock is already set by Set")
	}

	expectation := &LoggerAliasMockErrorfExpectation{
		mock:               mmErrorf.mock,
		params:             &LoggerAliasMockErrorfParams{message, args},
		expectationOrigins: LoggerAliasMockErrorfExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmErrorf.expectations = append(mmErrorf.expectations, expectation)
	return expectation
}

// Then sets up loggerAlias.Errorf return parameters for the expectation previously defined by the When method

func (e *LoggerAliasMockErrorfExpectation) Then() *LoggerAliasMock {
	return e.mock
}

// Times sets number of times loggerAlias.Errorf should be invoked
func (mmErrorf *mLoggerAliasMockErrorf) Times(n uint64) *mLoggerAliasMockErrorf {
	if n == 0 {
		mmErrorf.mock.t.Fatalf("Times of LoggerAliasMock.Errorf mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmErrorf.expectedInvocations, n)
	mmErrorf.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmErrorf
}

func (mmErrorf *mLoggerAliasMockErrorf) invocationsDone() bool {
	if len(mmErrorf.expectations) == 0 && mmErrorf.defaultExpectation == nil && mmErrorf.mock.funcErrorf == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmErrorf.mock.afterErrorfCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmErrorf.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Errorf implements loggerAlias
func (mmErrorf *LoggerAliasMock) Errorf(message string, args ...any) {
	mm_atomic.AddUint64(&mmErrorf.beforeErrorfCounter, 1)
	defer mm_atomic.AddUint64(&mmErrorf.afterErrorfCounter, 1)

	mmErrorf.t.Helper()

	if mmErrorf.inspectFuncErrorf != nil {
		mmErrorf.inspectFuncErrorf(message, args...)
	}

	mm_params := LoggerAliasMockErrorfParams{message, args}

	// Record call args
	mmErrorf.ErrorfMock.mutex.Lock()
	mmErrorf.ErrorfMock.callArgs = append(mmErrorf.ErrorfMock.callArgs, &mm_params)
	mmErrorf.ErrorfMock.mutex.Unlock()

	for _, e := range mmErrorf.ErrorfMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmErrorf.ErrorfMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmErrorf.ErrorfMock.defaultExpectation.Counter, 1)
		mm_want := mmErrorf.ErrorfMock.defaultExpectation.params
		mm_want_ptrs := mmErrorf.ErrorfMock.defaultExpectation.paramPtrs

		mm_got := LoggerAliasMockErrorfParams{message, args}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.message != nil && !minimock.Equal(*mm_want_ptrs.message, mm_got.message) {
				mmErrorf.t.Errorf("LoggerAliasMock.Errorf got unexpected parameter message, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmErrorf.ErrorfMock.defaultExpectation.expectationOrigins.originMessage, *mm_want_ptrs.message, mm_got.message, minimock.Diff(*mm_want_ptrs.message, mm_got.message))
			}

			if mm_want_ptrs.args != nil && !minimock.Equal(*mm_want_ptrs.args, mm_got.args) {
				mmErrorf.t.Errorf("LoggerAliasMock.Errorf got unexpected parameter args, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmErrorf.ErrorfMock.defaultExpectation.expectationOrigins.originArgs, *mm_want_ptrs.args, mm_got.args, minimock.Diff(*mm_want_ptrs.args, mm_got.args))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmErrorf.t.Errorf("LoggerAliasMock.Errorf got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmErrorf.ErrorfMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmErrorf.funcErrorf != nil {
		mmErrorf.funcErrorf(message, args...)
		return
	}
	mmErrorf.t.Fatalf("Unexpected call to LoggerAliasMock.Errorf. %v %v", message, args)

}

// ErrorfAfterCounter returns a count of finished LoggerAliasMock.Errorf invocations
func (mmErrorf *LoggerAliasMock) ErrorfAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmErrorf.afterErrorfCounter)
}

// ErrorfBeforeCounter returns a count of LoggerAliasMock.Errorf invocations
func (mmErrorf *LoggerAliasMock) ErrorfBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmErrorf.beforeErrorfCounter)
}

// Calls returns a list of arguments used in each call to LoggerAliasMock.Errorf.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmErrorf *mLoggerAliasMockErrorf) Calls() []*LoggerAliasMockErrorfParams {
	mmErrorf.mutex.RLock()

	argCopy := make([]*LoggerAliasMockErrorfParams, len(mmErrorf.callArgs))
	copy(argCopy, mmErrorf.callArgs)

	mmErrorf.mutex.RUnlock()

	return argCopy
}

// MinimockErrorfDone returns true if the count of the Errorf invocations corresponds
// the number of defined expectations
func (m *LoggerAliasMock) MinimockErrorfDone() bool {
	if m.ErrorfMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ErrorfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ErrorfMock.invocationsDone()
}

// MinimockErrorfInspect logs each unmet expectation
func (m *LoggerAliasMock) MinimockErrorfInspect() {
	for _, e := range m.ErrorfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LoggerAliasMock.Errorf at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterErrorfCounter := mm_atomic.LoadUint64(&m.afterErrorfCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ErrorfMock.defaultExpectation != nil && afterErrorfCounter < 1 {
		if m.ErrorfMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LoggerAliasMock.Errorf at\n%s", m.ErrorfMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LoggerAliasMock.Errorf at\n%s with params: %#v", m.ErrorfMock.defaultExpectation.expectationOrigins.origin, *m.ErrorfMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcErrorf != nil && afterErrorfCounter < 1 {
		m.t.Errorf("Expected call to LoggerAliasMock.Errorf at\n%s", m.funcErrorfOrigin)
	}

	if !m.ErrorfMock.invocationsDone() && afterErrorfCounter > 0 {
		m.t.Errorf("Expected %d calls to LoggerAliasMock.Errorf at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ErrorfMock.expectedInvocations), m.ErrorfMock.expectedInvocationsOrigin, afterErrorfCounter)
	}
}

type mLoggerAliasMockFatalf struct {
	optional           bool
	mock               *LoggerAliasMock
	defaultExpectation *LoggerAliasMockFatalfExpectation
	expectations       []*LoggerAliasMockFatalfExpectation

	callArgs []*LoggerAliasMockFatalfParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LoggerAliasMockFatalfExpectation specifies expectation struct of the loggerAlias.Fatalf
type LoggerAliasMockFatalfExpectation struct {
	mock               *LoggerAliasMock
	params             *LoggerAliasMockFatalfParams
	paramPtrs          *LoggerAliasMockFatalfParamPtrs
	expectationOrigins LoggerAliasMockFatalfExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// LoggerAliasMockFatalfParams contains parameters of the loggerAlias.Fatalf
type LoggerAliasMockFatalfParams struct {
	message string
	args    []any
}

// LoggerAliasMockFatalfParamPtrs contains pointers to parameters of the loggerAlias.Fatalf
type LoggerAliasMockFatalfParamPtrs struct {
	message *string
	args    *[]any
}

// LoggerAliasMockFatalfOrigins contains origins of expectations of the loggerAlias.Fatalf
type LoggerAliasMockFatalfExpectationOrigins struct {
	origin        string
	originMessage string
	originArgs    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmFatalf *mLoggerAliasMockFatalf) Optional() *mLoggerAliasMockFatalf {
	mmFatalf.optional = true
	return mmFatalf
}

// Expect sets up expected params for loggerAlias.Fatalf
func (mmFatalf *mLoggerAliasMockFatalf) Expect(message string, args ...any) *mLoggerAliasMockFatalf {
	if mmFatalf.mock.funcFatalf != nil {
		mmFatalf.mock.t.Fatalf("LoggerAliasMock.Fatalf mock is already set by Set")
	}

	if mmFatalf.defaultExpectation == nil {
		mmFatalf.defaultExpectation = &LoggerAliasMockFatalfExpectation{}
	}

	if mmFatalf.defaultExpectation.paramPtrs != nil {
		mmFatalf.mock.t.Fatalf("LoggerAliasMock.Fatalf mock is already set by ExpectParams functions")
	}

	mmFatalf.defaultExpectation.params = &LoggerAliasMockFatalfParams{message, args}
	mmFatalf.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmFatalf.expectations {
		if minimock.Equal(e.params, mmFatalf.defaultExpectation.params) {
			mmFatalf.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFatalf.defaultExpectation.params)
		}
	}

	return mmFatalf
}

// ExpectMessageParam1 sets up expected param message for loggerAlias.Fatalf
func (mmFatalf *mLoggerAliasMockFatalf) ExpectMessageParam1(message string) *mLoggerAliasMockFatalf {
	if mmFatalf.mock.funcFatalf != nil {
		mmFatalf.mock.t.Fatalf("LoggerAliasMock.Fatalf mock is already set by Set")
	}

	if mmFatalf.defaultExpectation == nil {
		mmFatalf.defaultExpectation = &LoggerAliasMockFatalfExpectation{}
	}

	if mmFatalf.defaultExpectation.params != nil {
		mmFatalf.mock.t.Fatalf("LoggerAliasMock.Fatalf mock is already set by Expect")
	}

	if mmFatalf.defaultExpectation.paramPtrs == nil {
		mmFatalf.defaultExpectation.paramPtrs = &LoggerAliasMockFatalfParamPtrs{}
	}
	mmFatalf.defaultExpectation.paramPtrs.message = &message
	mmFatalf.defaultExpectation.expectationOrigins.originMessage = minimock.CallerInfo(1)

	return mmFatalf
}

// ExpectArgsParam2 sets up expected param args for loggerAlias.Fatalf
func (mmFatalf *mLoggerAliasMockFatalf) ExpectArgsParam2(args ...any) *mLoggerAliasMockFatalf {
	if mmFatalf.mock.funcFatalf != nil {
		mmFatalf.mock.t.Fatalf("LoggerAliasMock.Fatalf mock is already set by Set")
	}

	if mmFatalf.defaultExpectation == nil {
		mmFatalf.defaultExpectation = &LoggerAliasMockFatalfExpectation{}
	}

	if mmFatalf.defaultExpectation.params != nil {
		mmFatalf.mock.t.Fatalf("LoggerAliasMock.Fatalf mock is already set by Expect")
	}

	if mmFatalf.defaultExpectation.paramPtrs == nil {
		mmFatalf.defaultExpectation.paramPtrs = &LoggerAliasMockFatalfParamPtrs{}
	}
	mmFatalf.defaultExpectation.paramPtrs.args = &args
	mmFatalf.defaultExpectation.expectationOrigins.originArgs = minimock.CallerInfo(1)

	return mmFatalf
}

// Inspect accepts an inspector function that has same arguments as the loggerAlias.Fatalf
func (mmFatalf *mLoggerAliasMockFatalf) Inspect(f func(message string, args ...any)) *mLoggerAliasMockFatalf {
	if mmFatalf.mock.inspectFuncFatalf != nil {
		mmFatalf.mock.t.Fatalf("Inspect function is already set for LoggerAliasMock.Fatalf")
	}

	mmFatalf.mock.inspectFuncFatalf = f

	return mmFatalf
}

// Return sets up results that will be returned by loggerAlias.Fatalf
func (mmFatalf *mLoggerAliasMockFatalf) Return() *LoggerAliasMock {
	if mmFatalf.mock.funcFatalf != nil {
		mmFatalf.mock.t.Fatalf("LoggerAliasMock.Fatalf mock is already set by Set")
	}

	if mmFatalf.defaultExpectation == nil {
		mmFatalf.defaultExpectation = &LoggerAliasMockFatalfExpectation{mock: mmFatalf.mock}
	}

	mmFatalf.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmFatalf.mock
}

// Set uses given function f to mock the loggerAlias.Fatalf method
func (mmFatalf *mLoggerAliasMockFatalf) Set(f func(message string, args ...any)) *LoggerAliasMock {
	if mmFatalf.defaultExpectation != nil {
		mmFatalf.mock.t.Fatalf("Default expectation is already set for the loggerAlias.Fatalf method")
	}

	if len(mmFatalf.expectations) > 0 {
		mmFatalf.mock.t.Fatalf("Some expectations are already set for the loggerAlias.Fatalf method")
	}

	mmFatalf.mock.funcFatalf = f
	mmFatalf.mock.funcFatalfOrigin = minimock.CallerInfo(1)
	return mmFatalf.mock
}

// When sets expectation for the loggerAlias.Fatalf which will trigger the result defined by the following
// Then helper
func (mmFatalf *mLoggerAliasMockFatalf) When(message string, args ...any) *LoggerAliasMockFatalfExpectation {
	if mmFatalf.mock.funcFatalf != nil {
		mmFatalf.mock.t.Fatalf("LoggerAliasMock.Fatalf mock is already set by Set")
	}

	expectation := &LoggerAliasMockFatalfExpectation{
		mock:               mmFatalf.mock,
		params:             &LoggerAliasMockFatalfParams{message, args},
		expectationOrigins: LoggerAliasMockFatalfExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmFatalf.expectations = append(mmFatalf.expectations, expectation)
	return expectation
}

// Then sets up loggerAlias.Fatalf return parameters for the expectation previously defined by the When method

func (e *LoggerAliasMockFatalfExpectation) Then() *LoggerAliasMock {
	return e.mock
}

// Times sets number of times loggerAlias.Fatalf should be invoked
func (mmFatalf *mLoggerAliasMockFatalf) Times(n uint64) *mLoggerAliasMockFatalf {
	if n == 0 {
		mmFatalf.mock.t.Fatalf("Times of LoggerAliasMock.Fatalf mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmFatalf.expectedInvocations, n)
	mmFatalf.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmFatalf
}

func (mmFatalf *mLoggerAliasMockFatalf) invocationsDone() bool {
	if len(mmFatalf.expectations) == 0 && mmFatalf.defaultExpectation == nil && mmFatalf.mock.funcFatalf == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmFatalf.mock.afterFatalfCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmFatalf.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Fatalf implements loggerAlias
func (mmFatalf *LoggerAliasMock) Fatalf(message string, args ...any) {
	mm_atomic.AddUint64(&mmFatalf.beforeFatalfCounter, 1)
	defer mm_atomic.AddUint64(&mmFatalf.afterFatalfCounter, 1)

	mmFatalf.t.Helper()

	if mmFatalf.inspectFuncFatalf != nil {
		mmFatalf.inspectFuncFatalf(message, args...)
	}

	mm_params := LoggerAliasMockFatalfParams{message, args}

	// Record call args
	mmFatalf.FatalfMock.mutex.Lock()
	mmFatalf.FatalfMock.callArgs = append(mmFatalf.FatalfMock.callArgs, &mm_params)
	mmFatalf.FatalfMock.mutex.Unlock()

	for _, e := range mmFatalf.FatalfMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmFatalf.FatalfMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFatalf.FatalfMock.defaultExpectation.Counter, 1)
		mm_want := mmFatalf.FatalfMock.defaultExpectation.params
		mm_want_ptrs := mmFatalf.FatalfMock.defaultExpectation.paramPtrs

		mm_got := LoggerAliasMockFatalfParams{message, args}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.message != nil && !minimock.Equal(*mm_want_ptrs.message, mm_got.message) {
				mmFatalf.t.Errorf("LoggerAliasMock.Fatalf got unexpected parameter message, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFatalf.FatalfMock.defaultExpectation.expectationOrigins.originMessage, *mm_want_ptrs.message, mm_got.message, minimock.Diff(*mm_want_ptrs.message, mm_got.message))
			}

			if mm_want_ptrs.args != nil && !minimock.Equal(*mm_want_ptrs.args, mm_got.args) {
				mmFatalf.t.Errorf("LoggerAliasMock.Fatalf got unexpected parameter args, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFatalf.FatalfMock.defaultExpectation.expectationOrigins.originArgs, *mm_want_ptrs.args, mm_got.args, minimock.Diff(*mm_want_ptrs.args, mm_got.args))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFatalf.t.Errorf("LoggerAliasMock.Fatalf got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmFatalf.FatalfMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmFatalf.funcFatalf != nil {
		mmFatalf.funcFatalf(message, args...)
		return
	}
	mmFatalf.t.Fatalf("Unexpected call to LoggerAliasMock.Fatalf. %v %v", message, args)

}

// FatalfAfterCounter returns a count of finished LoggerAliasMock.Fatalf invocations
func (mmFatalf *LoggerAliasMock) FatalfAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFatalf.afterFatalfCounter)
}

// FatalfBeforeCounter returns a count of LoggerAliasMock.Fatalf invocations
func (mmFatalf *LoggerAliasMock) FatalfBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFatalf.beforeFatalfCounter)
}

// Calls returns a list of arguments used in each call to LoggerAliasMock.Fatalf.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFatalf *mLoggerAliasMockFatalf) Calls() []*LoggerAliasMockFatalfParams {
	mmFatalf.mutex.RLock()

	argCopy := make([]*LoggerAliasMockFatalfParams, len(mmFatalf.callArgs))
	copy(argCopy, mmFatalf.callArgs)

	mmFatalf.mutex.RUnlock()

	return argCopy
}

// MinimockFatalfDone returns true if the count of the Fatalf invocations corresponds
// the number of defined expectations
func (m *LoggerAliasMock) MinimockFatalfDone() bool {
	if m.FatalfMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.FatalfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.FatalfMock.invocationsDone()
}

// MinimockFatalfInspect logs each unmet expectation
func (m *LoggerAliasMock) MinimockFatalfInspect() {
	for _, e := range m.FatalfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LoggerAliasMock.Fatalf at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterFatalfCounter := mm_atomic.LoadUint64(&m.afterFatalfCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.FatalfMock.defaultExpectation != nil && afterFatalfCounter < 1 {
		if m.FatalfMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LoggerAliasMock.Fatalf at\n%s", m.FatalfMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LoggerAliasMock.Fatalf at\n%s with params: %#v", m.FatalfMock.defaultExpectation.expectationOrigins.origin, *m.FatalfMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFatalf != nil && afterFatalfCounter < 1 {
		m.t.Errorf("Expected call to LoggerAliasMock.Fatalf at\n%s", m.funcFatalfOrigin)
	}

	if !m.FatalfMock.invocationsDone() && afterFatalfCounter > 0 {
		m.t.Errorf("Expected %d calls to LoggerAliasMock.Fatalf at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.FatalfMock.expectedInvocations), m.FatalfMock.expectedInvocationsOrigin, afterFatalfCounter)
	}
}

type mLoggerAliasMockInfof struct {
	optional           bool
	mock               *LoggerAliasMock
	defaultExpectation *LoggerAliasMockInfofExpectation
	expectations       []*LoggerAliasMockInfofExpectation

	callArgs []*LoggerAliasMockInfofParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LoggerAliasMockInfofExpectation specifies expectation struct of the loggerAlias.Infof
type LoggerAliasMockInfofExpectation struct {
	mock               *LoggerAliasMock
	params             *LoggerAliasMockInfofParams
	paramPtrs          *LoggerAliasMockInfofParamPtrs
	expectationOrigins LoggerAliasMockInfofExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// LoggerAliasMockInfofParams contains parameters of the loggerAlias.Infof
type LoggerAliasMockInfofParams struct {
	message string
	args    []any
}

// LoggerAliasMockInfofParamPtrs contains pointers to parameters of the loggerAlias.Infof
type LoggerAliasMockInfofParamPtrs struct {
	message *string
	args    *[]any
}

// LoggerAliasMockInfofOrigins contains origins of expectations of the loggerAlias.Infof
type LoggerAliasMockInfofExpectationOrigins struct {
	origin        string
	originMessage string
	originArgs    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInfof *mLoggerAliasMockInfof) Optional() *mLoggerAliasMockInfof {
	mmInfof.optional = true
	return mmInfof
}

// Expect sets up expected params for loggerAlias.Infof
func (mmInfof *mLoggerAliasMockInfof) Expect(message string, args ...any) *mLoggerAliasMockInfof {
	if mmInfof.mock.funcInfof != nil {
		mmInfof.mock.t.Fatalf("LoggerAliasMock.Infof mock is already set by Set")
	}

	if mmInfof.defaultExpectation == nil {
		mmInfof.defaultExpectation = &LoggerAliasMockInfofExpectation{}
	}

	if mmInfof.defaultExpectation.paramPtrs != nil {
		mmInfof.mock.t.Fatalf("LoggerAliasMock.Infof mock is already set by ExpectParams functions")
	}

	mmInfof.defaultExpectation.params = &LoggerAliasMockInfofParams{message, args}
	mmInfof.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInfof.expectations {
		if minimock.Equal(e.params, mmInfof.defaultExpectation.params) {
			mmInfof.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInfof.defaultExpectation.params)
		}
	}

	return mmInfof
}

// ExpectMessageParam1 sets up expected param message for loggerAlias.Infof
func (mmInfof *mLoggerAliasMockInfof) ExpectMessageParam1(message string) *mLoggerAliasMockInfof {
	if mmInfof.mock.funcInfof != nil {
		mmInfof.mock.t.Fatalf("LoggerAliasMock.Infof mock is already set by Set")
	}

	if mmInfof.defaultExpectation == nil {
		mmInfof.defaultExpectation = &LoggerAliasMockInfofExpectation{}
	}

	if mmInfof.defaultExpectation.params != nil {
		mmInfof.mock.t.Fatalf("LoggerAliasMock.Infof mock is already set by Expect")
	}

	if mmInfof.defaultExpectation.paramPtrs == nil {
		mmInfof.defaultExpectation.paramPtrs = &LoggerAliasMockInfofParamPtrs{}
	}
	mmInfof.defaultExpectation.paramPtrs.message = &message
	mmInfof.defaultExpectation.expectationOrigins.originMessage = minimock.CallerInfo(1)

	return mmInfof
}

// ExpectArgsParam2 sets up expected param args for loggerAlias.Infof
func (mmInfof *mLoggerAliasMockInfof) ExpectArgsParam2(args ...any) *mLoggerAliasMockInfof {
	if mmInfof.mock.funcInfof != nil {
		mmInfof.mock.t.Fatalf("LoggerAliasMock.Infof mock is already set by Set")
	}

	if mmInfof.defaultExpectation == nil {
		mmInfof.defaultExpectation = &LoggerAliasMockInfofExpectation{}
	}

	if mmInfof.defaultExpectation.params != nil {
		mmInfof.mock.t.Fatalf("LoggerAliasMock.Infof mock is already set by Expect")
	}

	if mmInfof.defaultExpectation.paramPtrs == nil {
		mmInfof.defaultExpectation.paramPtrs = &LoggerAliasMockInfofParamPtrs{}
	}
	mmInfof.defaultExpectation.paramPtrs.args = &args
	mmInfof.defaultExpectation.expectationOrigins.originArgs = minimock.CallerInfo(1)

	return mmInfof
}

// Inspect accepts an inspector function that has same arguments as the loggerAlias.Infof
func (mmInfof *mLoggerAliasMockInfof) Inspect(f func(message string, args ...any)) *mLoggerAliasMockInfof {
	if mmInfof.mock.inspectFuncInfof != nil {
		mmInfof.mock.t.Fatalf("Inspect function is already set for LoggerAliasMock.Infof")
	}

	mmInfof.mock.inspectFuncInfof = f

	return mmInfof
}

// Return sets up results that will be returned by loggerAlias.Infof
func (mmInfof *mLoggerAliasMockInfof) Return() *LoggerAliasMock {
	if mmInfof.mock.funcInfof != nil {
		mmInfof.mock.t.Fatalf("LoggerAliasMock.Infof mock is already set by Set")
	}

	if mmInfof.defaultExpectation == nil {
		mmInfof.defaultExpectation = &LoggerAliasMockInfofExpectation{mock: mmInfof.mock}
	}

	mmInfof.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInfof.mock
}

// Set uses given function f to mock the loggerAlias.Infof method
func (mmInfof *mLoggerAliasMockInfof) Set(f func(message string, args ...any)) *LoggerAliasMock {
	if mmInfof.defaultExpectation != nil {
		mmInfof.mock.t.Fatalf("Default expectation is already set for the loggerAlias.Infof method")
	}

	if len(mmInfof.expectations) > 0 {
		mmInfof.mock.t.Fatalf("Some expectations are already set for the loggerAlias.Infof method")
	}

	mmInfof.mock.funcInfof = f
	mmInfof.mock.funcInfofOrigin = minimock.CallerInfo(1)
	return mmInfof.mock
}

// When sets expectation for the loggerAlias.Infof which will trigger the result defined by the following
// Then helper
func (mmInfof *mLoggerAliasMockInfof) When(message string, args ...any) *LoggerAliasMockInfofExpectation {
	if mmInfof.mock.funcInfof != nil {
		mmInfof.mock.t.Fatalf("LoggerAliasMock.Infof mock is already set by Set")
	}

	expectation := &LoggerAliasMockInfofExpectation{
		mock:               mmInfof.mock,
		params:             &LoggerAliasMockInfofParams{message, args},
		expectationOrigins: LoggerAliasMockInfofExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInfof.expectations = append(mmInfof.expectations, expectation)
	return expectation
}

// Then sets up loggerAlias.Infof return parameters for the expectation previously defined by the When method

func (e *LoggerAliasMockInfofExpectation) Then() *LoggerAliasMock {
	return e.mock
}

// Times sets number of times loggerAlias.Infof should be invoked
func (mmInfof *mLoggerAliasMockInfof) Times(n uint64) *mLoggerAliasMockInfof {
	if n == 0 {
		mmInfof.mock.t.Fatalf("Times of LoggerAliasMock.Infof mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInfof.expectedInvocations, n)
	mmInfof.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInfof
}

func (mmInfof *mLoggerAliasMockInfof) invocationsDone() bool {
	if len(mmInfof.expectations) == 0 && mmInfof.defaultExpectation == nil && mmInfof.mock.funcInfof == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInfof.mock.afterInfofCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInfof.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Infof implements loggerAlias
func (mmInfof *LoggerAliasMock) Infof(message string, args ...any) {
	mm_atomic.AddUint64(&mmInfof.beforeInfofCounter, 1)
	defer mm_atomic.AddUint64(&mmInfof.afterInfofCounter, 1)

	mmInfof.t.Helper()

	if mmInfof.inspectFuncInfof != nil {
		mmInfof.inspectFuncInfof(message, args...)
	}

	mm_params := LoggerAliasMockInfofParams{message, args}

	// Record call args
	mmInfof.InfofMock.mutex.Lock()
	mmInfof.InfofMock.callArgs = append(mmInfof.InfofMock.callArgs, &mm_params)
	mmInfof.InfofMock.mutex.Unlock()

	for _, e := range mmInfof.InfofMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmInfof.InfofMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInfof.InfofMock.defaultExpectation.Counter, 1)
		mm_want := mmInfof.InfofMock.defaultExpectation.params
		mm_want_ptrs := mmInfof.InfofMock.defaultExpectation.paramPtrs

		mm_got := LoggerAliasMockInfofParams{message, args}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.message != nil && !minimock.Equal(*mm_want_ptrs.message, mm_got.message) {
				mmInfof.t.Errorf("LoggerAliasMock.Infof got unexpected parameter message, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInfof.InfofMock.defaultExpectation.expectationOrigins.originMessage, *mm_want_ptrs.message, mm_got.message, minimock.Diff(*mm_want_ptrs.message, mm_got.message))
			}

			if mm_want_ptrs.args != nil && !minimock.Equal(*mm_want_ptrs.args, mm_got.args) {
				mmInfof.t.Errorf("LoggerAliasMock.Infof got unexpected parameter args, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInfof.InfofMock.defaultExpectation.expectationOrigins.originArgs, *mm_want_ptrs.args, mm_got.args, minimock.Diff(*mm_want_ptrs.args, mm_got.args))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInfof.t.Errorf("LoggerAliasMock.Infof got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInfof.InfofMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmInfof.funcInfof != nil {
		mmInfof.funcInfof(message, args...)
		return
	}
	mmInfof.t.Fatalf("Unexpected call to LoggerAliasMock.Infof. %v %v", message, args)

}

// InfofAfterCounter returns a count of finished LoggerAliasMock.Infof invocations
func (mmInfof *LoggerAliasMock) InfofAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInfof.afterInfofCounter)
}

// InfofBeforeCounter returns a count of LoggerAliasMock.Infof invocations
func (mmInfof *LoggerAliasMock) InfofBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInfof.beforeInfofCounter)
}

// Calls returns a list of arguments used in each call to LoggerAliasMock.Infof.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInfof *mLoggerAliasMockInfof) Calls() []*LoggerAliasMockInfofParams {
	mmInfof.mutex.RLock()

	argCopy := make([]*LoggerAliasMockInfofParams, len(mmInfof.callArgs))
	copy(argCopy, mmInfof.callArgs)

	mmInfof.mutex.RUnlock()

	return argCopy
}

// MinimockInfofDone returns true if the count of the Infof invocations corresponds
// the number of defined expectations
func (m *LoggerAliasMock) MinimockInfofDone() bool {
	if m.InfofMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InfofMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InfofMock.invocationsDone()
}

// MinimockInfofInspect logs each unmet expectation
func (m *LoggerAliasMock) MinimockInfofInspect() {
	for _, e := range m.InfofMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LoggerAliasMock.Infof at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInfofCounter := mm_atomic.LoadUint64(&m.afterInfofCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InfofMock.defaultExpectation != nil && afterInfofCounter < 1 {
		if m.InfofMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LoggerAliasMock.Infof at\n%s", m.InfofMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LoggerAliasMock.Infof at\n%s with params: %#v", m.InfofMock.defaultExpectation.expectationOrigins.origin, *m.InfofMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInfof != nil && afterInfofCounter < 1 {
		m.t.Errorf("Expected call to LoggerAliasMock.Infof at\n%s", m.funcInfofOrigin)
	}

	if !m.InfofMock.invocationsDone() && afterInfofCounter > 0 {
		m.t.Errorf("Expected %d calls to LoggerAliasMock.Infof at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InfofMock.expectedInvocations), m.InfofMock.expectedInvocationsOrigin, afterInfofCounter)
	}
}

type mLoggerAliasMockSync struct {
	optional           bool
	mock               *LoggerAliasMock
	defaultExpectation *LoggerAliasMockSyncExpectation
	expectations       []*LoggerAliasMockSyncExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LoggerAliasMockSyncExpectation specifies expectation struct of the loggerAlias.Sync
type LoggerAliasMockSyncExpectation struct {
	mock *LoggerAliasMock

	results      *LoggerAliasMockSyncResults
	returnOrigin string
	Counter      uint64
}

// LoggerAliasMockSyncResults contains results of the loggerAlias.Sync
type LoggerAliasMockSyncResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSync *mLoggerAliasMockSync) Optional() *mLoggerAliasMockSync {
	mmSync.optional = true
	return mmSync
}

// Expect sets up expected params for loggerAlias.Sync
func (mmSync *mLoggerAliasMockSync) Expect() *mLoggerAliasMockSync {
	if mmSync.mock.funcSync != nil {
		mmSync.mock.t.Fatalf("LoggerAliasMock.Sync mock is already set by Set")
	}

	if mmSync.defaultExpectation == nil {
		mmSync.defaultExpectation = &LoggerAliasMockSyncExpectation{}
	}

	return mmSync
}

// Inspect accepts an inspector function that has same arguments as the loggerAlias.Sync
func (mmSync *mLoggerAliasMockSync) Inspect(f func()) *mLoggerAliasMockSync {
	if mmSync.mock.inspectFuncSync != nil {
		mmSync.mock.t.Fatalf("Inspect function is already set for LoggerAliasMock.Sync")
	}

	mmSync.mock.inspectFuncSync = f

	return mmSync
}

// Return sets up results that will be returned by loggerAlias.Sync
func (mmSync *mLoggerAliasMockSync) Return(err error) *LoggerAliasMock {
	if mmSync.mock.funcSync != nil {
		mmSync.mock.t.Fatalf("LoggerAliasMock.Sync mock is already set by Set")
	}

	if mmSync.defaultExpectation == nil {
		mmSync.defaultExpectation = &LoggerAliasMockSyncExpectation{mock: mmSync.mock}
	}
	mmSync.defaultExpectation.results = &LoggerAliasMockSyncResults{err}
	mmSync.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSync.mock
}

// Set uses given function f to mock the loggerAlias.Sync method
func (mmSync *mLoggerAliasMockSync) Set(f func() (err error)) *LoggerAliasMock {
	if mmSync.defaultExpectation != nil {
		mmSync.mock.t.Fatalf("Default expectation is already set for the loggerAlias.Sync method")
	}

	if len(mmSync.expectations) > 0 {
		mmSync.mock.t.Fatalf("Some expectations are already set for the loggerAlias.Sync method")
	}

	mmSync.mock.funcSync = f
	mmSync.mock.funcSyncOrigin = minimock.CallerInfo(1)
	return mmSync.mock
}

// Times sets number of times loggerAlias.Sync should be invoked
func (mmSync *mLoggerAliasMockSync) Times(n uint64) *mLoggerAliasMockSync {
	if n == 0 {
		mmSync.mock.t.Fatalf("Times of LoggerAliasMock.Sync mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSync.expectedInvocations, n)
	mmSync.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSync
}

func (mmSync *mLoggerAliasMockSync) invocationsDone() bool {
	if len(mmSync.expectations) == 0 && mmSync.defaultExpectation == nil && mmSync.mock.funcSync == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSync.mock.afterSyncCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSync.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Sync implements loggerAlias
func (mmSync *LoggerAliasMock) Sync() (err error) {
	mm_atomic.AddUint64(&mmSync.beforeSyncCounter, 1)
	defer mm_atomic.AddUint64(&mmSync.afterSyncCounter, 1)

	mmSync.t.Helper()

	if mmSync.inspectFuncSync != nil {
		mmSync.inspectFuncSync()
	}

	if mmSync.SyncMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSync.SyncMock.defaultExpectation.Counter, 1)

		mm_results := mmSync.SyncMock.defaultExpectation.results
		if mm_results == nil {
			mmSync.t.Fatal("No results are set for the LoggerAliasMock.Sync")
		}
		return (*mm_results).err
	}
	if mmSync.funcSync != nil {
		return mmSync.funcSync()
	}
	mmSync.t.Fatalf("Unexpected call to LoggerAliasMock.Sync.")
	return
}

// SyncAfterCounter returns a count of finished LoggerAliasMock.Sync invocations
func (mmSync *LoggerAliasMock) SyncAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSync.afterSyncCounter)
}

// SyncBeforeCounter returns a count of LoggerAliasMock.Sync invocations
func (mmSync *LoggerAliasMock) SyncBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSync.beforeSyncCounter)
}

// MinimockSyncDone returns true if the count of the Sync invocations corresponds
// the number of defined expectations
func (m *LoggerAliasMock) MinimockSyncDone() bool {
	if m.SyncMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SyncMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SyncMock.invocationsDone()
}

// MinimockSyncInspect logs each unmet expectation
func (m *LoggerAliasMock) MinimockSyncInspect() {
	for _, e := range m.SyncMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to LoggerAliasMock.Sync")
		}
	}

	afterSyncCounter := mm_atomic.LoadUint64(&m.afterSyncCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SyncMock.defaultExpectation != nil && afterSyncCounter < 1 {
		m.t.Errorf("Expected call to LoggerAliasMock.Sync at\n%s", m.SyncMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSync != nil && afterSyncCounter < 1 {
		m.t.Errorf("Expected call to LoggerAliasMock.Sync at\n%s", m.funcSyncOrigin)
	}

	if !m.SyncMock.invocationsDone() && afterSyncCounter > 0 {
		m.t.Errorf("Expected %d calls to LoggerAliasMock.Sync at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SyncMock.expectedInvocations), m.SyncMock.expectedInvocationsOrigin, afterSyncCounter)
	}
}

type mLoggerAliasMockWarnf struct {
	optional           bool
	mock               *LoggerAliasMock
	defaultExpectation *LoggerAliasMockWarnfExpectation
	expectations       []*LoggerAliasMockWarnfExpectation

	callArgs []*LoggerAliasMockWarnfParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LoggerAliasMockWarnfExpectation specifies expectation struct of the loggerAlias.Warnf
type LoggerAliasMockWarnfExpectation struct {
	mock               *LoggerAliasMock
	params             *LoggerAliasMockWarnfParams
	paramPtrs          *LoggerAliasMockWarnfParamPtrs
	expectationOrigins LoggerAliasMockWarnfExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// LoggerAliasMockWarnfParams contains parameters of the loggerAlias.Warnf
type LoggerAliasMockWarnfParams struct {
	message string
	args    []any
}

// LoggerAliasMockWarnfParamPtrs contains pointers to parameters of the loggerAlias.Warnf
type LoggerAliasMockWarnfParamPtrs struct {
	message *string
	args    *[]any
}

// LoggerAliasMockWarnfOrigins contains origins of expectations of the loggerAlias.Warnf
type LoggerAliasMockWarnfExpectationOrigins struct {
	origin        string
	originMessage string
	originArgs    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmWarnf *mLoggerAliasMockWarnf) Optional() *mLoggerAliasMockWarnf {
	mmWarnf.optional = true
	return mmWarnf
}

// Expect sets up expected params for loggerAlias.Warnf
func (mmWarnf *mLoggerAliasMockWarnf) Expect(message string, args ...any) *mLoggerAliasMockWarnf {
	if mmWarnf.mock.funcWarnf != nil {
		mmWarnf.mock.t.Fatalf("LoggerAliasMock.Warnf mock is already set by Set")
	}

	if mmWarnf.defaultExpectation == nil {
		mmWarnf.defaultExpectation = &LoggerAliasMockWarnfExpectation{}
	}

	if mmWarnf.defaultExpectation.paramPtrs != nil {
		mmWarnf.mock.t.Fatalf("LoggerAliasMock.Warnf mock is already set by ExpectParams functions")
	}

	mmWarnf.defaultExpectation.params = &LoggerAliasMockWarnfParams{message, args}
	mmWarnf.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmWarnf.expectations {
		if minimock.Equal(e.params, mmWarnf.defaultExpectation.params) {
			mmWarnf.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWarnf.defaultExpectation.params)
		}
	}

	return mmWarnf
}

// ExpectMessageParam1 sets up expected param message for loggerAlias.Warnf
func (mmWarnf *mLoggerAliasMockWarnf) ExpectMessageParam1(message string) *mLoggerAliasMockWarnf {
	if mmWarnf.mock.funcWarnf != nil {
		mmWarnf.mock.t.Fatalf("LoggerAliasMock.Warnf mock is already set by Set")
	}

	if mmWarnf.defaultExpectation == nil {
		mmWarnf.defaultExpectation = &LoggerAliasMockWarnfExpectation{}
	}

	if mmWarnf.defaultExpectation.params != nil {
		mmWarnf.mock.t.Fatalf("LoggerAliasMock.Warnf mock is already set by Expect")
	}

	if mmWarnf.defaultExpectation.paramPtrs == nil {
		mmWarnf.defaultExpectation.paramPtrs = &LoggerAliasMockWarnfParamPtrs{}
	}
	mmWarnf.defaultExpectation.paramPtrs.message = &message
	mmWarnf.defaultExpectation.expectationOrigins.originMessage = minimock.CallerInfo(1)

	return mmWarnf
}

// ExpectArgsParam2 sets up expected param args for loggerAlias.Warnf
func (mmWarnf *mLoggerAliasMockWarnf) ExpectArgsParam2(args ...any) *mLoggerAliasMockWarnf {
	if mmWarnf.mock.funcWarnf != nil {
		mmWarnf.mock.t.Fatalf("LoggerAliasMock.Warnf mock is already set by Set")
	}

	if mmWarnf.defaultExpectation == nil {
		mmWarnf.defaultExpectation = &LoggerAliasMockWarnfExpectation{}
	}

	if mmWarnf.defaultExpectation.params != nil {
		mmWarnf.mock.t.Fatalf("LoggerAliasMock.Warnf mock is already set by Expect")
	}

	if mmWarnf.defaultExpectation.paramPtrs == nil {
		mmWarnf.defaultExpectation.paramPtrs = &LoggerAliasMockWarnfParamPtrs{}
	}
	mmWarnf.defaultExpectation.paramPtrs.args = &args
	mmWarnf.defaultExpectation.expectationOrigins.originArgs = minimock.CallerInfo(1)

	return mmWarnf
}

// Inspect accepts an inspector function that has same arguments as the loggerAlias.Warnf
func (mmWarnf *mLoggerAliasMockWarnf) Inspect(f func(message string, args ...any)) *mLoggerAliasMockWarnf {
	if mmWarnf.mock.inspectFuncWarnf != nil {
		mmWarnf.mock.t.Fatalf("Inspect function is already set for LoggerAliasMock.Warnf")
	}

	mmWarnf.mock.inspectFuncWarnf = f

	return mmWarnf
}

// Return sets up results that will be returned by loggerAlias.Warnf
func (mmWarnf *mLoggerAliasMockWarnf) Return() *LoggerAliasMock {
	if mmWarnf.mock.funcWarnf != nil {
		mmWarnf.mock.t.Fatalf("LoggerAliasMock.Warnf mock is already set by Set")
	}

	if mmWarnf.defaultExpectation == nil {
		mmWarnf.defaultExpectation = &LoggerAliasMockWarnfExpectation{mock: mmWarnf.mock}
	}

	mmWarnf.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmWarnf.mock
}

// Set uses given function f to mock the loggerAlias.Warnf method
func (mmWarnf *mLoggerAliasMockWarnf) Set(f func(message string, args ...any)) *LoggerAliasMock {
	if mmWarnf.defaultExpectation != nil {
		mmWarnf.mock.t.Fatalf("Default expectation is already set for the loggerAlias.Warnf method")
	}

	if len(mmWarnf.expectations) > 0 {
		mmWarnf.mock.t.Fatalf("Some expectations are already set for the loggerAlias.Warnf method")
	}

	mmWarnf.mock.funcWarnf = f
	mmWarnf.mock.funcWarnfOrigin = minimock.CallerInfo(1)
	return mmWarnf.mock
}

// When sets expectation for the loggerAlias.Warnf which will trigger the result defined by the following
// Then helper
func (mmWarnf *mLoggerAliasMockWarnf) When(message string, args ...any) *LoggerAliasMockWarnfExpectation {
	if mmWarnf.mock.funcWarnf != nil {
		mmWarnf.mock.t.Fatalf("LoggerAliasMock.Warnf mock is already set by Set")
	}

	expectation := &LoggerAliasMockWarnfExpectation{
		mock:               mmWarnf.mock,
		params:             &LoggerAliasMockWarnfParams{message, args},
		expectationOrigins: LoggerAliasMockWarnfExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmWarnf.expectations = append(mmWarnf.expectations, expectation)
	return expectation
}

// Then sets up loggerAlias.Warnf return parameters for the expectation previously defined by the When method

func (e *LoggerAliasMockWarnfExpectation) Then() *LoggerAliasMock {
	return e.mock
}

// Times sets number of times loggerAlias.Warnf should be invoked
func (mmWarnf *mLoggerAliasMockWarnf) Times(n uint64) *mLoggerAliasMockWarnf {
	if n == 0 {
		mmWarnf.mock.t.Fatalf("Times of LoggerAliasMock.Warnf mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmWarnf.expectedInvocations, n)
	mmWarnf.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmWarnf
}

func (mmWarnf *mLoggerAliasMockWarnf) invocationsDone() bool {
	if len(mmWarnf.expectations) == 0 && mmWarnf.defaultExpectation == nil && mmWarnf.mock.funcWarnf == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmWarnf.mock.afterWarnfCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmWarnf.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Warnf implements loggerAlias
func (mmWarnf *LoggerAliasMock) Warnf(message string, args ...any) {
	mm_atomic.AddUint64(&mmWarnf.beforeWarnfCounter, 1)
	defer mm_atomic.AddUint64(&mmWarnf.afterWarnfCounter, 1)

	mmWarnf.t.Helper()

	if mmWarnf.inspectFuncWarnf != nil {
		mmWarnf.inspectFuncWarnf(message, args...)
	}

	mm_params := LoggerAliasMockWarnfParams{message, args}

	// Record call args
	mmWarnf.WarnfMock.mutex.Lock()
	mmWarnf.WarnfMock.callArgs = append(mmWarnf.WarnfMock.callArgs, &mm_params)
	mmWarnf.WarnfMock.mutex.Unlock()

	for _, e := range mmWarnf.WarnfMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmWarnf.WarnfMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWarnf.WarnfMock.defaultExpectation.Counter, 1)
		mm_want := mmWarnf.WarnfMock.defaultExpectation.params
		mm_want_ptrs := mmWarnf.WarnfMock.defaultExpectation.paramPtrs

		mm_got := LoggerAliasMockWarnfParams{message, args}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.message != nil && !minimock.Equal(*mm_want_ptrs.message, mm_got.message) {
				mmWarnf.t.Errorf("LoggerAliasMock.Warnf got unexpected parameter message, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWarnf.WarnfMock.defaultExpectation.expectationOrigins.originMessage, *mm_want_ptrs.message, mm_got.message, minimock.Diff(*mm_want_ptrs.message, mm_got.message))
			}

			if mm_want_ptrs.args != nil && !minimock.Equal(*mm_want_ptrs.args, mm_got.args) {
				mmWarnf.t.Errorf("LoggerAliasMock.Warnf got unexpected parameter args, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWarnf.WarnfMock.defaultExpectation.expectationOrigins.originArgs, *mm_want_ptrs.args, mm_got.args, minimock.Diff(*mm_want_ptrs.args, mm_got.args))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWarnf.t.Errorf("LoggerAliasMock.Warnf got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmWarnf.WarnfMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmWarnf.funcWarnf != nil {
		mmWarnf.funcWarnf(message, args...)
		return
	}
	mmWarnf.t.Fatalf("Unexpected call to LoggerAliasMock.Warnf. %v %v", message, args)

}

// WarnfAfterCounter returns a count of finished LoggerAliasMock.Warnf invocations
func (mmWarnf *LoggerAliasMock) WarnfAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWarnf.afterWarnfCounter)
}

// WarnfBeforeCounter returns a count of LoggerAliasMock.Warnf invocations
func (mmWarnf *LoggerAliasMock) WarnfBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWarnf.beforeWarnfCounter)
}

// Calls returns a list of arguments used in each call to LoggerAliasMock.Warnf.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWarnf *mLoggerAliasMockWarnf) Calls() []*LoggerAliasMockWarnfParams {
	mmWarnf.mutex.RLock()

	argCopy := make([]*LoggerAliasMockWarnfParams, len(mmWarnf.callArgs))
	copy(argCopy, mmWarnf.callArgs)

	mmWarnf.mutex.RUnlock()

	return argCopy
}

// MinimockWarnfDone returns true if the count of the Warnf invocations corresponds
// the number of defined expectations
func (m *LoggerAliasMock) MinimockWarnfDone() bool {
	if m.WarnfMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.WarnfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.WarnfMock.invocationsDone()
}

// MinimockWarnfInspect logs each unmet expectation
func (m *LoggerAliasMock) MinimockWarnfInspect() {
	for _, e := range m.WarnfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LoggerAliasMock.Warnf at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterWarnfCounter := mm_atomic.LoadUint64(&m.afterWarnfCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.WarnfMock.defaultExpectation != nil && afterWarnfCounter < 1 {
		if m.WarnfMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LoggerAliasMock.Warnf at\n%s", m.WarnfMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LoggerAliasMock.Warnf at\n%s with params: %#v", m.WarnfMock.defaultExpectation.expectationOrigins.origin, *m.WarnfMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWarnf != nil && afterWarnfCounter < 1 {
		m.t.Errorf("Expected call to LoggerAliasMock.Warnf at\n%s", m.funcWarnfOrigin)
	}

	if !m.WarnfMock.invocationsDone() && afterWarnfCounter > 0 {
		m.t.Errorf("Expected %d calls to LoggerAliasMock.Warnf at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.WarnfMock.expectedInvocations), m.WarnfMock.expectedInvocationsOrigin, afterWarnfCounter)
	}
}

type mLoggerAliasMockWithf struct {
	optional           bool
	mock               *LoggerAliasMock
	defaultExpectation *LoggerAliasMockWithfExpectation
	expectations       []*LoggerAliasMockWithfExpectation

	callArgs []*LoggerAliasMockWithfParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LoggerAliasMockWithfExpectation specifies expectation struct of the loggerAlias.Withf
type LoggerAliasMockWithfExpectation struct {
	mock               *LoggerAliasMock
	params             *LoggerAliasMockWithfParams
	paramPtrs          *LoggerAliasMockWithfParamPtrs
	expectationOrigins LoggerAliasMockWithfExpectationOrigins
	results            *LoggerAliasMockWithfResults
	returnOrigin       string
	Counter            uint64
}

// LoggerAliasMockWithfParams contains parameters of the loggerAlias.Withf
type LoggerAliasMockWithfParams struct {
	key   logger.Field
	value any
}

// LoggerAliasMockWithfParamPtrs contains pointers to parameters of the loggerAlias.Withf
type LoggerAliasMockWithfParamPtrs struct {
	key   *logger.Field
	value *any
}

// LoggerAliasMockWithfResults contains results of the loggerAlias.Withf
type LoggerAliasMockWithfResults struct {
	l1 logger.Logger
}

// LoggerAliasMockWithfOrigins contains origins of expectations of the loggerAlias.Withf
type LoggerAliasMockWithfExpectationOrigins struct {
	origin      string
	originKey   string
	originValue string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmWithf *mLoggerAliasMockWithf) Optional() *mLoggerAliasMockWithf {
	mmWithf.optional = true
	return mmWithf
}

// Expect sets up expected params for loggerAlias.Withf
func (mmWithf *mLoggerAliasMockWithf) Expect(key logger.Field, value any) *mLoggerAliasMockWithf {
	if mmWithf.mock.funcWithf != nil {
		mmWithf.mock.t.Fatalf("LoggerAliasMock.Withf mock is already set by Set")
	}

	if mmWithf.defaultExpectation == nil {
		mmWithf.defaultExpectation = &LoggerAliasMockWithfExpectation{}
	}

	if mmWithf.defaultExpectation.paramPtrs != nil {
		mmWithf.mock.t.Fatalf("LoggerAliasMock.Withf mock is already set by ExpectParams functions")
	}

	mmWithf.defaultExpectation.params = &LoggerAliasMockWithfParams{key, value}
	mmWithf.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmWithf.expectations {
		if minimock.Equal(e.params, mmWithf.defaultExpectation.params) {
			mmWithf.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWithf.defaultExpectation.params)
		}
	}

	return mmWithf
}

// ExpectKeyParam1 sets up expected param key for loggerAlias.Withf
func (mmWithf *mLoggerAliasMockWithf) ExpectKeyParam1(key logger.Field) *mLoggerAliasMockWithf {
	if mmWithf.mock.funcWithf != nil {
		mmWithf.mock.t.Fatalf("LoggerAliasMock.Withf mock is already set by Set")
	}

	if mmWithf.defaultExpectation == nil {
		mmWithf.defaultExpectation = &LoggerAliasMockWithfExpectation{}
	}

	if mmWithf.defaultExpectation.params != nil {
		mmWithf.mock.t.Fatalf("LoggerAliasMock.Withf mock is already set by Expect")
	}

	if mmWithf.defaultExpectation.paramPtrs == nil {
		mmWithf.defaultExpectation.paramPtrs = &LoggerAliasMockWithfParamPtrs{}
	}
	mmWithf.defaultExpectation.paramPtrs.key = &key
	mmWithf.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmWithf
}

// ExpectValueParam2 sets up expected param value for loggerAlias.Withf
func (mmWithf *mLoggerAliasMockWithf) ExpectValueParam2(value any) *mLoggerAliasMockWithf {
	if mmWithf.mock.funcWithf != nil {
		mmWithf.mock.t.Fatalf("LoggerAliasMock.Withf mock is already set by Set")
	}

	if mmWithf.defaultExpectation == nil {
		mmWithf.defaultExpectation = &LoggerAliasMockWithfExpectation{}
	}

	if mmWithf.defaultExpectation.params != nil {
		mmWithf.mock.t.Fatalf("LoggerAliasMock.Withf mock is already set by Expect")
	}

	if mmWithf.defaultExpectation.paramPtrs == nil {
		mmWithf.defaultExpectation.paramPtrs = &LoggerAliasMockWithfParamPtrs{}
	}
	mmWithf.defaultExpectation.paramPtrs.value = &value
	mmWithf.defaultExpectation.expectationOrigins.originValue = minimock.CallerInfo(1)

	return mmWithf
}

// Inspect accepts an inspector function that has same arguments as the loggerAlias.Withf
func (mmWithf *mLoggerAliasMockWithf) Inspect(f func(key logger.Field, value any)) *mLoggerAliasMockWithf {
	if mmWithf.mock.inspectFuncWithf != nil {
		mmWithf.mock.t.Fatalf("Inspect function is already set for LoggerAliasMock.Withf")
	}

	mmWithf.mock.inspectFuncWithf = f

	return mmWithf
}

// Return sets up results that will be returned by loggerAlias.Withf
func (mmWithf *mLoggerAliasMockWithf) Return(l1 logger.Logger) *LoggerAliasMock {
	if mmWithf.mock.funcWithf != nil {
		mmWithf.mock.t.Fatalf("LoggerAliasMock.Withf mock is already set by Set")
	}

	if mmWithf.defaultExpectation == nil {
		mmWithf.defaultExpectation = &LoggerAliasMockWithfExpectation{mock: mmWithf.mock}
	}
	mmWithf.defaultExpectation.results = &LoggerAliasMockWithfResults{l1}
	mmWithf.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmWithf.mock
}

// Set uses given function f to mock the loggerAlias.Withf method
func (mmWithf *mLoggerAliasMockWithf) Set(f func(key logger.Field, value any) (l1 logger.Logger)) *LoggerAliasMock {
	if mmWithf.defaultExpectation != nil {
		mmWithf.mock.t.Fatalf("Default expectation is already set for the loggerAlias.Withf method")
	}

	if len(mmWithf.expectations) > 0 {
		mmWithf.mock.t.Fatalf("Some expectations are already set for the loggerAlias.Withf method")
	}

	mmWithf.mock.funcWithf = f
	mmWithf.mock.funcWithfOrigin = minimock.CallerInfo(1)
	return mmWithf.mock
}

// When sets expectation for the loggerAlias.Withf which will trigger the result defined by the following
// Then helper
func (mmWithf *mLoggerAliasMockWithf) When(key logger.Field, value any) *LoggerAliasMockWithfExpectation {
	if mmWithf.mock.funcWithf != nil {
		mmWithf.mock.t.Fatalf("LoggerAliasMock.Withf mock is already set by Set")
	}

	expectation := &LoggerAliasMockWithfExpectation{
		mock:               mmWithf.mock,
		params:             &LoggerAliasMockWithfParams{key, value},
		expectationOrigins: LoggerAliasMockWithfExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmWithf.expectations = append(mmWithf.expectations, expectation)
	return expectation
}

// Then sets up loggerAlias.Withf return parameters for the expectation previously defined by the When method
func (e *LoggerAliasMockWithfExpectation) Then(l1 logger.Logger) *LoggerAliasMock {
	e.results = &LoggerAliasMockWithfResults{l1}
	return e.mock
}

// Times sets number of times loggerAlias.Withf should be invoked
func (mmWithf *mLoggerAliasMockWithf) Times(n uint64) *mLoggerAliasMockWithf {
	if n == 0 {
		mmWithf.mock.t.Fatalf("Times of LoggerAliasMock.Withf mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmWithf.expectedInvocations, n)
	mmWithf.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmWithf
}

func (mmWithf *mLoggerAliasMockWithf) invocationsDone() bool {
	if len(mmWithf.expectations) == 0 && mmWithf.defaultExpectation == nil && mmWithf.mock.funcWithf == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmWithf.mock.afterWithfCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmWithf.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Withf implements loggerAlias
func (mmWithf *LoggerAliasMock) Withf(key logger.Field, value any) (l1 logger.Logger) {
	mm_atomic.AddUint64(&mmWithf.beforeWithfCounter, 1)
	defer mm_atomic.AddUint64(&mmWithf.afterWithfCounter, 1)

	mmWithf.t.Helper()

	if mmWithf.inspectFuncWithf != nil {
		mmWithf.inspectFuncWithf(key, value)
	}

	mm_params := LoggerAliasMockWithfParams{key, value}

	// Record call args
	mmWithf.WithfMock.mutex.Lock()
	mmWithf.WithfMock.callArgs = append(mmWithf.WithfMock.callArgs, &mm_params)
	mmWithf.WithfMock.mutex.Unlock()

	for _, e := range mmWithf.WithfMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.l1
		}
	}

	if mmWithf.WithfMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWithf.WithfMock.defaultExpectation.Counter, 1)
		mm_want := mmWithf.WithfMock.defaultExpectation.params
		mm_want_ptrs := mmWithf.WithfMock.defaultExpectation.paramPtrs

		mm_got := LoggerAliasMockWithfParams{key, value}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmWithf.t.Errorf("LoggerAliasMock.Withf got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWithf.WithfMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.value != nil && !minimock.Equal(*mm_want_ptrs.value, mm_got.value) {
				mmWithf.t.Errorf("LoggerAliasMock.Withf got unexpected parameter value, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWithf.WithfMock.defaultExpectation.expectationOrigins.originValue, *mm_want_ptrs.value, mm_got.value, minimock.Diff(*mm_want_ptrs.value, mm_got.value))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWithf.t.Errorf("LoggerAliasMock.Withf got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmWithf.WithfMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWithf.WithfMock.defaultExpectation.results
		if mm_results == nil {
			mmWithf.t.Fatal("No results are set for the LoggerAliasMock.Withf")
		}
		return (*mm_results).l1
	}
	if mmWithf.funcWithf != nil {
		return mmWithf.funcWithf(key, value)
	}
	mmWithf.t.Fatalf("Unexpected call to LoggerAliasMock.Withf. %v %v", key, value)
	return
}

// WithfAfterCounter returns a count of finished LoggerAliasMock.Withf invocations
func (mmWithf *LoggerAliasMock) WithfAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWithf.afterWithfCounter)
}

// WithfBeforeCounter returns a count of LoggerAliasMock.Withf invocations
func (mmWithf *LoggerAliasMock) WithfBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWithf.beforeWithfCounter)
}

// Calls returns a list of arguments used in each call to LoggerAliasMock.Withf.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWithf *mLoggerAliasMockWithf) Calls() []*LoggerAliasMockWithfParams {
	mmWithf.mutex.RLock()

	argCopy := make([]*LoggerAliasMockWithfParams, len(mmWithf.callArgs))
	copy(argCopy, mmWithf.callArgs)

	mmWithf.mutex.RUnlock()

	return argCopy
}

// MinimockWithfDone returns true if the count of the Withf invocations corresponds
// the number of defined expectations
func (m *LoggerAliasMock) MinimockWithfDone() bool {
	if m.WithfMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.WithfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.WithfMock.invocationsDone()
}

// MinimockWithfInspect logs each unmet expectation
func (m *LoggerAliasMock) MinimockWithfInspect() {
	for _, e := range m.WithfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LoggerAliasMock.Withf at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterWithfCounter := mm_atomic.LoadUint64(&m.afterWithfCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.WithfMock.defaultExpectation != nil && afterWithfCounter < 1 {
		if m.WithfMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LoggerAliasMock.Withf at\n%s", m.WithfMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LoggerAliasMock.Withf at\n%s with params: %#v", m.WithfMock.defaultExpectation.expectationOrigins.origin, *m.WithfMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWithf != nil && afterWithfCounter < 1 {
		m.t.Errorf("Expected call to LoggerAliasMock.Withf at\n%s", m.funcWithfOrigin)
	}

	if !m.WithfMock.invocationsDone() && afterWithfCounter > 0 {
		m.t.Errorf("Expected %d calls to LoggerAliasMock.Withf at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.WithfMock.expectedInvocations), m.WithfMock.expectedInvocationsOrigin, afterWithfCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LoggerAliasMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDebugfInspect()

			m.MinimockErrorfInspect()

			m.MinimockFatalfInspect()

			m.MinimockInfofInspect()

			m.MinimockSyncInspect()

			m.MinimockWarnfInspect()

			m.MinimockWithfInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LoggerAliasMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LoggerAliasMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDebugfDone() &&
		m.MinimockErrorfDone() &&
		m.MinimockFatalfDone() &&
		m.MinimockInfofDone() &&
		m.MinimockSyncDone() &&
		m.MinimockWarnfDone() &&
		m.MinimockWithfDone()
}
