// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i ed_in_memory_database/internal/service/database.storageLayer -o compute.mock.gen.go -n StorageLayerMock -p mocks

import (
	"context"
	"ed_in_memory_database/internal/entity/storing_types"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// StorageLayerMock implements mm_database.storageLayer
type StorageLayerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDelete          func(ctx context.Context, key storing_types.KeyStr) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, key storing_types.KeyStr)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mStorageLayerMockDelete

	funcGet          func(ctx context.Context, key storing_types.KeyStr) (v1 storing_types.ValueStr, err error)
	funcGetOrigin    string
	inspectFuncGet   func(ctx context.Context, key storing_types.KeyStr)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mStorageLayerMockGet

	funcSet          func(ctx context.Context, key storing_types.KeyStr, value storing_types.ValueStr) (err error)
	funcSetOrigin    string
	inspectFuncSet   func(ctx context.Context, key storing_types.KeyStr, value storing_types.ValueStr)
	afterSetCounter  uint64
	beforeSetCounter uint64
	SetMock          mStorageLayerMockSet
}

// NewStorageLayerMock returns a mock for mm_database.storageLayer
func NewStorageLayerMock(t minimock.Tester) *StorageLayerMock {
	m := &StorageLayerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteMock = mStorageLayerMockDelete{mock: m}
	m.DeleteMock.callArgs = []*StorageLayerMockDeleteParams{}

	m.GetMock = mStorageLayerMockGet{mock: m}
	m.GetMock.callArgs = []*StorageLayerMockGetParams{}

	m.SetMock = mStorageLayerMockSet{mock: m}
	m.SetMock.callArgs = []*StorageLayerMockSetParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStorageLayerMockDelete struct {
	optional           bool
	mock               *StorageLayerMock
	defaultExpectation *StorageLayerMockDeleteExpectation
	expectations       []*StorageLayerMockDeleteExpectation

	callArgs []*StorageLayerMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageLayerMockDeleteExpectation specifies expectation struct of the storageLayer.Delete
type StorageLayerMockDeleteExpectation struct {
	mock               *StorageLayerMock
	params             *StorageLayerMockDeleteParams
	paramPtrs          *StorageLayerMockDeleteParamPtrs
	expectationOrigins StorageLayerMockDeleteExpectationOrigins
	results            *StorageLayerMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// StorageLayerMockDeleteParams contains parameters of the storageLayer.Delete
type StorageLayerMockDeleteParams struct {
	ctx context.Context
	key storing_types.KeyStr
}

// StorageLayerMockDeleteParamPtrs contains pointers to parameters of the storageLayer.Delete
type StorageLayerMockDeleteParamPtrs struct {
	ctx *context.Context
	key *storing_types.KeyStr
}

// StorageLayerMockDeleteResults contains results of the storageLayer.Delete
type StorageLayerMockDeleteResults struct {
	err error
}

// StorageLayerMockDeleteOrigins contains origins of expectations of the storageLayer.Delete
type StorageLayerMockDeleteExpectationOrigins struct {
	origin    string
	originCtx string
	originKey string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mStorageLayerMockDelete) Optional() *mStorageLayerMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for storageLayer.Delete
func (mmDelete *mStorageLayerMockDelete) Expect(ctx context.Context, key storing_types.KeyStr) *mStorageLayerMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StorageLayerMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &StorageLayerMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("StorageLayerMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &StorageLayerMockDeleteParams{ctx, key}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for storageLayer.Delete
func (mmDelete *mStorageLayerMockDelete) ExpectCtxParam1(ctx context.Context) *mStorageLayerMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StorageLayerMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &StorageLayerMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("StorageLayerMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &StorageLayerMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectKeyParam2 sets up expected param key for storageLayer.Delete
func (mmDelete *mStorageLayerMockDelete) ExpectKeyParam2(key storing_types.KeyStr) *mStorageLayerMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StorageLayerMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &StorageLayerMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("StorageLayerMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &StorageLayerMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.key = &key
	mmDelete.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the storageLayer.Delete
func (mmDelete *mStorageLayerMockDelete) Inspect(f func(ctx context.Context, key storing_types.KeyStr)) *mStorageLayerMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for StorageLayerMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by storageLayer.Delete
func (mmDelete *mStorageLayerMockDelete) Return(err error) *StorageLayerMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StorageLayerMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &StorageLayerMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &StorageLayerMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the storageLayer.Delete method
func (mmDelete *mStorageLayerMockDelete) Set(f func(ctx context.Context, key storing_types.KeyStr) (err error)) *StorageLayerMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the storageLayer.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the storageLayer.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the storageLayer.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mStorageLayerMockDelete) When(ctx context.Context, key storing_types.KeyStr) *StorageLayerMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("StorageLayerMock.Delete mock is already set by Set")
	}

	expectation := &StorageLayerMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &StorageLayerMockDeleteParams{ctx, key},
		expectationOrigins: StorageLayerMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up storageLayer.Delete return parameters for the expectation previously defined by the When method
func (e *StorageLayerMockDeleteExpectation) Then(err error) *StorageLayerMock {
	e.results = &StorageLayerMockDeleteResults{err}
	return e.mock
}

// Times sets number of times storageLayer.Delete should be invoked
func (mmDelete *mStorageLayerMockDelete) Times(n uint64) *mStorageLayerMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of StorageLayerMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mStorageLayerMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_database.storageLayer
func (mmDelete *StorageLayerMock) Delete(ctx context.Context, key storing_types.KeyStr) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, key)
	}

	mm_params := StorageLayerMockDeleteParams{ctx, key}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := StorageLayerMockDeleteParams{ctx, key}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("StorageLayerMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmDelete.t.Errorf("StorageLayerMock.Delete got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("StorageLayerMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the StorageLayerMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, key)
	}
	mmDelete.t.Fatalf("Unexpected call to StorageLayerMock.Delete. %v %v", ctx, key)
	return
}

// DeleteAfterCounter returns a count of finished StorageLayerMock.Delete invocations
func (mmDelete *StorageLayerMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of StorageLayerMock.Delete invocations
func (mmDelete *StorageLayerMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to StorageLayerMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mStorageLayerMockDelete) Calls() []*StorageLayerMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*StorageLayerMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *StorageLayerMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *StorageLayerMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageLayerMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageLayerMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageLayerMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to StorageLayerMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageLayerMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mStorageLayerMockGet struct {
	optional           bool
	mock               *StorageLayerMock
	defaultExpectation *StorageLayerMockGetExpectation
	expectations       []*StorageLayerMockGetExpectation

	callArgs []*StorageLayerMockGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageLayerMockGetExpectation specifies expectation struct of the storageLayer.Get
type StorageLayerMockGetExpectation struct {
	mock               *StorageLayerMock
	params             *StorageLayerMockGetParams
	paramPtrs          *StorageLayerMockGetParamPtrs
	expectationOrigins StorageLayerMockGetExpectationOrigins
	results            *StorageLayerMockGetResults
	returnOrigin       string
	Counter            uint64
}

// StorageLayerMockGetParams contains parameters of the storageLayer.Get
type StorageLayerMockGetParams struct {
	ctx context.Context
	key storing_types.KeyStr
}

// StorageLayerMockGetParamPtrs contains pointers to parameters of the storageLayer.Get
type StorageLayerMockGetParamPtrs struct {
	ctx *context.Context
	key *storing_types.KeyStr
}

// StorageLayerMockGetResults contains results of the storageLayer.Get
type StorageLayerMockGetResults struct {
	v1  storing_types.ValueStr
	err error
}

// StorageLayerMockGetOrigins contains origins of expectations of the storageLayer.Get
type StorageLayerMockGetExpectationOrigins struct {
	origin    string
	originCtx string
	originKey string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mStorageLayerMockGet) Optional() *mStorageLayerMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for storageLayer.Get
func (mmGet *mStorageLayerMockGet) Expect(ctx context.Context, key storing_types.KeyStr) *mStorageLayerMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StorageLayerMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &StorageLayerMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("StorageLayerMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &StorageLayerMockGetParams{ctx, key}
	mmGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectCtxParam1 sets up expected param ctx for storageLayer.Get
func (mmGet *mStorageLayerMockGet) ExpectCtxParam1(ctx context.Context) *mStorageLayerMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StorageLayerMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &StorageLayerMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("StorageLayerMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &StorageLayerMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.ctx = &ctx
	mmGet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGet
}

// ExpectKeyParam2 sets up expected param key for storageLayer.Get
func (mmGet *mStorageLayerMockGet) ExpectKeyParam2(key storing_types.KeyStr) *mStorageLayerMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StorageLayerMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &StorageLayerMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("StorageLayerMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &StorageLayerMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.key = &key
	mmGet.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the storageLayer.Get
func (mmGet *mStorageLayerMockGet) Inspect(f func(ctx context.Context, key storing_types.KeyStr)) *mStorageLayerMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for StorageLayerMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by storageLayer.Get
func (mmGet *mStorageLayerMockGet) Return(v1 storing_types.ValueStr, err error) *StorageLayerMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StorageLayerMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &StorageLayerMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &StorageLayerMockGetResults{v1, err}
	mmGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// Set uses given function f to mock the storageLayer.Get method
func (mmGet *mStorageLayerMockGet) Set(f func(ctx context.Context, key storing_types.KeyStr) (v1 storing_types.ValueStr, err error)) *StorageLayerMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the storageLayer.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the storageLayer.Get method")
	}

	mmGet.mock.funcGet = f
	mmGet.mock.funcGetOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// When sets expectation for the storageLayer.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mStorageLayerMockGet) When(ctx context.Context, key storing_types.KeyStr) *StorageLayerMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("StorageLayerMock.Get mock is already set by Set")
	}

	expectation := &StorageLayerMockGetExpectation{
		mock:               mmGet.mock,
		params:             &StorageLayerMockGetParams{ctx, key},
		expectationOrigins: StorageLayerMockGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up storageLayer.Get return parameters for the expectation previously defined by the When method
func (e *StorageLayerMockGetExpectation) Then(v1 storing_types.ValueStr, err error) *StorageLayerMock {
	e.results = &StorageLayerMockGetResults{v1, err}
	return e.mock
}

// Times sets number of times storageLayer.Get should be invoked
func (mmGet *mStorageLayerMockGet) Times(n uint64) *mStorageLayerMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of StorageLayerMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	mmGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGet
}

func (mmGet *mStorageLayerMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements mm_database.storageLayer
func (mmGet *StorageLayerMock) Get(ctx context.Context, key storing_types.KeyStr) (v1 storing_types.ValueStr, err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	mmGet.t.Helper()

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, key)
	}

	mm_params := StorageLayerMockGetParams{ctx, key}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.v1, e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := StorageLayerMockGetParams{ctx, key}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGet.t.Errorf("StorageLayerMock.Get got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmGet.t.Errorf("StorageLayerMock.Get got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("StorageLayerMock.Get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGet.GetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the StorageLayerMock.Get")
		}
		return (*mm_results).v1, (*mm_results).err
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, key)
	}
	mmGet.t.Fatalf("Unexpected call to StorageLayerMock.Get. %v %v", ctx, key)
	return
}

// GetAfterCounter returns a count of finished StorageLayerMock.Get invocations
func (mmGet *StorageLayerMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of StorageLayerMock.Get invocations
func (mmGet *StorageLayerMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to StorageLayerMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mStorageLayerMockGet) Calls() []*StorageLayerMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*StorageLayerMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *StorageLayerMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *StorageLayerMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageLayerMock.Get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageLayerMock.Get at\n%s", m.GetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageLayerMock.Get at\n%s with params: %#v", m.GetMock.defaultExpectation.expectationOrigins.origin, *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Errorf("Expected call to StorageLayerMock.Get at\n%s", m.funcGetOrigin)
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageLayerMock.Get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), m.GetMock.expectedInvocationsOrigin, afterGetCounter)
	}
}

type mStorageLayerMockSet struct {
	optional           bool
	mock               *StorageLayerMock
	defaultExpectation *StorageLayerMockSetExpectation
	expectations       []*StorageLayerMockSetExpectation

	callArgs []*StorageLayerMockSetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageLayerMockSetExpectation specifies expectation struct of the storageLayer.Set
type StorageLayerMockSetExpectation struct {
	mock               *StorageLayerMock
	params             *StorageLayerMockSetParams
	paramPtrs          *StorageLayerMockSetParamPtrs
	expectationOrigins StorageLayerMockSetExpectationOrigins
	results            *StorageLayerMockSetResults
	returnOrigin       string
	Counter            uint64
}

// StorageLayerMockSetParams contains parameters of the storageLayer.Set
type StorageLayerMockSetParams struct {
	ctx   context.Context
	key   storing_types.KeyStr
	value storing_types.ValueStr
}

// StorageLayerMockSetParamPtrs contains pointers to parameters of the storageLayer.Set
type StorageLayerMockSetParamPtrs struct {
	ctx   *context.Context
	key   *storing_types.KeyStr
	value *storing_types.ValueStr
}

// StorageLayerMockSetResults contains results of the storageLayer.Set
type StorageLayerMockSetResults struct {
	err error
}

// StorageLayerMockSetOrigins contains origins of expectations of the storageLayer.Set
type StorageLayerMockSetExpectationOrigins struct {
	origin      string
	originCtx   string
	originKey   string
	originValue string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSet *mStorageLayerMockSet) Optional() *mStorageLayerMockSet {
	mmSet.optional = true
	return mmSet
}

// Expect sets up expected params for storageLayer.Set
func (mmSet *mStorageLayerMockSet) Expect(ctx context.Context, key storing_types.KeyStr, value storing_types.ValueStr) *mStorageLayerMockSet {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &StorageLayerMockSetExpectation{}
	}

	if mmSet.defaultExpectation.paramPtrs != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by ExpectParams functions")
	}

	mmSet.defaultExpectation.params = &StorageLayerMockSetParams{ctx, key, value}
	mmSet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSet.expectations {
		if minimock.Equal(e.params, mmSet.defaultExpectation.params) {
			mmSet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSet.defaultExpectation.params)
		}
	}

	return mmSet
}

// ExpectCtxParam1 sets up expected param ctx for storageLayer.Set
func (mmSet *mStorageLayerMockSet) ExpectCtxParam1(ctx context.Context) *mStorageLayerMockSet {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &StorageLayerMockSetExpectation{}
	}

	if mmSet.defaultExpectation.params != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by Expect")
	}

	if mmSet.defaultExpectation.paramPtrs == nil {
		mmSet.defaultExpectation.paramPtrs = &StorageLayerMockSetParamPtrs{}
	}
	mmSet.defaultExpectation.paramPtrs.ctx = &ctx
	mmSet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSet
}

// ExpectKeyParam2 sets up expected param key for storageLayer.Set
func (mmSet *mStorageLayerMockSet) ExpectKeyParam2(key storing_types.KeyStr) *mStorageLayerMockSet {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &StorageLayerMockSetExpectation{}
	}

	if mmSet.defaultExpectation.params != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by Expect")
	}

	if mmSet.defaultExpectation.paramPtrs == nil {
		mmSet.defaultExpectation.paramPtrs = &StorageLayerMockSetParamPtrs{}
	}
	mmSet.defaultExpectation.paramPtrs.key = &key
	mmSet.defaultExpectation.expectationOrigins.originKey = minimock.CallerInfo(1)

	return mmSet
}

// ExpectValueParam3 sets up expected param value for storageLayer.Set
func (mmSet *mStorageLayerMockSet) ExpectValueParam3(value storing_types.ValueStr) *mStorageLayerMockSet {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &StorageLayerMockSetExpectation{}
	}

	if mmSet.defaultExpectation.params != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by Expect")
	}

	if mmSet.defaultExpectation.paramPtrs == nil {
		mmSet.defaultExpectation.paramPtrs = &StorageLayerMockSetParamPtrs{}
	}
	mmSet.defaultExpectation.paramPtrs.value = &value
	mmSet.defaultExpectation.expectationOrigins.originValue = minimock.CallerInfo(1)

	return mmSet
}

// Inspect accepts an inspector function that has same arguments as the storageLayer.Set
func (mmSet *mStorageLayerMockSet) Inspect(f func(ctx context.Context, key storing_types.KeyStr, value storing_types.ValueStr)) *mStorageLayerMockSet {
	if mmSet.mock.inspectFuncSet != nil {
		mmSet.mock.t.Fatalf("Inspect function is already set for StorageLayerMock.Set")
	}

	mmSet.mock.inspectFuncSet = f

	return mmSet
}

// Return sets up results that will be returned by storageLayer.Set
func (mmSet *mStorageLayerMockSet) Return(err error) *StorageLayerMock {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by Set")
	}

	if mmSet.defaultExpectation == nil {
		mmSet.defaultExpectation = &StorageLayerMockSetExpectation{mock: mmSet.mock}
	}
	mmSet.defaultExpectation.results = &StorageLayerMockSetResults{err}
	mmSet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSet.mock
}

// Set uses given function f to mock the storageLayer.Set method
func (mmSet *mStorageLayerMockSet) Set(f func(ctx context.Context, key storing_types.KeyStr, value storing_types.ValueStr) (err error)) *StorageLayerMock {
	if mmSet.defaultExpectation != nil {
		mmSet.mock.t.Fatalf("Default expectation is already set for the storageLayer.Set method")
	}

	if len(mmSet.expectations) > 0 {
		mmSet.mock.t.Fatalf("Some expectations are already set for the storageLayer.Set method")
	}

	mmSet.mock.funcSet = f
	mmSet.mock.funcSetOrigin = minimock.CallerInfo(1)
	return mmSet.mock
}

// When sets expectation for the storageLayer.Set which will trigger the result defined by the following
// Then helper
func (mmSet *mStorageLayerMockSet) When(ctx context.Context, key storing_types.KeyStr, value storing_types.ValueStr) *StorageLayerMockSetExpectation {
	if mmSet.mock.funcSet != nil {
		mmSet.mock.t.Fatalf("StorageLayerMock.Set mock is already set by Set")
	}

	expectation := &StorageLayerMockSetExpectation{
		mock:               mmSet.mock,
		params:             &StorageLayerMockSetParams{ctx, key, value},
		expectationOrigins: StorageLayerMockSetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSet.expectations = append(mmSet.expectations, expectation)
	return expectation
}

// Then sets up storageLayer.Set return parameters for the expectation previously defined by the When method
func (e *StorageLayerMockSetExpectation) Then(err error) *StorageLayerMock {
	e.results = &StorageLayerMockSetResults{err}
	return e.mock
}

// Times sets number of times storageLayer.Set should be invoked
func (mmSet *mStorageLayerMockSet) Times(n uint64) *mStorageLayerMockSet {
	if n == 0 {
		mmSet.mock.t.Fatalf("Times of StorageLayerMock.Set mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSet.expectedInvocations, n)
	mmSet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSet
}

func (mmSet *mStorageLayerMockSet) invocationsDone() bool {
	if len(mmSet.expectations) == 0 && mmSet.defaultExpectation == nil && mmSet.mock.funcSet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSet.mock.afterSetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Set implements mm_database.storageLayer
func (mmSet *StorageLayerMock) Set(ctx context.Context, key storing_types.KeyStr, value storing_types.ValueStr) (err error) {
	mm_atomic.AddUint64(&mmSet.beforeSetCounter, 1)
	defer mm_atomic.AddUint64(&mmSet.afterSetCounter, 1)

	mmSet.t.Helper()

	if mmSet.inspectFuncSet != nil {
		mmSet.inspectFuncSet(ctx, key, value)
	}

	mm_params := StorageLayerMockSetParams{ctx, key, value}

	// Record call args
	mmSet.SetMock.mutex.Lock()
	mmSet.SetMock.callArgs = append(mmSet.SetMock.callArgs, &mm_params)
	mmSet.SetMock.mutex.Unlock()

	for _, e := range mmSet.SetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSet.SetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSet.SetMock.defaultExpectation.Counter, 1)
		mm_want := mmSet.SetMock.defaultExpectation.params
		mm_want_ptrs := mmSet.SetMock.defaultExpectation.paramPtrs

		mm_got := StorageLayerMockSetParams{ctx, key, value}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSet.t.Errorf("StorageLayerMock.Set got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSet.SetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.key != nil && !minimock.Equal(*mm_want_ptrs.key, mm_got.key) {
				mmSet.t.Errorf("StorageLayerMock.Set got unexpected parameter key, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSet.SetMock.defaultExpectation.expectationOrigins.originKey, *mm_want_ptrs.key, mm_got.key, minimock.Diff(*mm_want_ptrs.key, mm_got.key))
			}

			if mm_want_ptrs.value != nil && !minimock.Equal(*mm_want_ptrs.value, mm_got.value) {
				mmSet.t.Errorf("StorageLayerMock.Set got unexpected parameter value, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSet.SetMock.defaultExpectation.expectationOrigins.originValue, *mm_want_ptrs.value, mm_got.value, minimock.Diff(*mm_want_ptrs.value, mm_got.value))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSet.t.Errorf("StorageLayerMock.Set got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSet.SetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSet.SetMock.defaultExpectation.results
		if mm_results == nil {
			mmSet.t.Fatal("No results are set for the StorageLayerMock.Set")
		}
		return (*mm_results).err
	}
	if mmSet.funcSet != nil {
		return mmSet.funcSet(ctx, key, value)
	}
	mmSet.t.Fatalf("Unexpected call to StorageLayerMock.Set. %v %v %v", ctx, key, value)
	return
}

// SetAfterCounter returns a count of finished StorageLayerMock.Set invocations
func (mmSet *StorageLayerMock) SetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSet.afterSetCounter)
}

// SetBeforeCounter returns a count of StorageLayerMock.Set invocations
func (mmSet *StorageLayerMock) SetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSet.beforeSetCounter)
}

// Calls returns a list of arguments used in each call to StorageLayerMock.Set.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSet *mStorageLayerMockSet) Calls() []*StorageLayerMockSetParams {
	mmSet.mutex.RLock()

	argCopy := make([]*StorageLayerMockSetParams, len(mmSet.callArgs))
	copy(argCopy, mmSet.callArgs)

	mmSet.mutex.RUnlock()

	return argCopy
}

// MinimockSetDone returns true if the count of the Set invocations corresponds
// the number of defined expectations
func (m *StorageLayerMock) MinimockSetDone() bool {
	if m.SetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SetMock.invocationsDone()
}

// MinimockSetInspect logs each unmet expectation
func (m *StorageLayerMock) MinimockSetInspect() {
	for _, e := range m.SetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageLayerMock.Set at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSetCounter := mm_atomic.LoadUint64(&m.afterSetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SetMock.defaultExpectation != nil && afterSetCounter < 1 {
		if m.SetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageLayerMock.Set at\n%s", m.SetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageLayerMock.Set at\n%s with params: %#v", m.SetMock.defaultExpectation.expectationOrigins.origin, *m.SetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSet != nil && afterSetCounter < 1 {
		m.t.Errorf("Expected call to StorageLayerMock.Set at\n%s", m.funcSetOrigin)
	}

	if !m.SetMock.invocationsDone() && afterSetCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageLayerMock.Set at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SetMock.expectedInvocations), m.SetMock.expectedInvocationsOrigin, afterSetCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StorageLayerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteInspect()

			m.MinimockGetInspect()

			m.MinimockSetInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StorageLayerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StorageLayerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteDone() &&
		m.MinimockGetDone() &&
		m.MinimockSetDone()
}
