// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i ed_in_memory_database/internal/service/database.computeLayer -o storage.mock.gen.go -n ComputeLayerMock -p mocks

import (
	"ed_in_memory_database/internal/entity"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ComputeLayerMock implements mm_database.computeLayer
type ComputeLayerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcParseQuery          func(rawQuery string) (c1 entity.Command, err error)
	funcParseQueryOrigin    string
	inspectFuncParseQuery   func(rawQuery string)
	afterParseQueryCounter  uint64
	beforeParseQueryCounter uint64
	ParseQueryMock          mComputeLayerMockParseQuery
}

// NewComputeLayerMock returns a mock for mm_database.computeLayer
func NewComputeLayerMock(t minimock.Tester) *ComputeLayerMock {
	m := &ComputeLayerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ParseQueryMock = mComputeLayerMockParseQuery{mock: m}
	m.ParseQueryMock.callArgs = []*ComputeLayerMockParseQueryParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mComputeLayerMockParseQuery struct {
	optional           bool
	mock               *ComputeLayerMock
	defaultExpectation *ComputeLayerMockParseQueryExpectation
	expectations       []*ComputeLayerMockParseQueryExpectation

	callArgs []*ComputeLayerMockParseQueryParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ComputeLayerMockParseQueryExpectation specifies expectation struct of the computeLayer.ParseQuery
type ComputeLayerMockParseQueryExpectation struct {
	mock               *ComputeLayerMock
	params             *ComputeLayerMockParseQueryParams
	paramPtrs          *ComputeLayerMockParseQueryParamPtrs
	expectationOrigins ComputeLayerMockParseQueryExpectationOrigins
	results            *ComputeLayerMockParseQueryResults
	returnOrigin       string
	Counter            uint64
}

// ComputeLayerMockParseQueryParams contains parameters of the computeLayer.ParseQuery
type ComputeLayerMockParseQueryParams struct {
	rawQuery string
}

// ComputeLayerMockParseQueryParamPtrs contains pointers to parameters of the computeLayer.ParseQuery
type ComputeLayerMockParseQueryParamPtrs struct {
	rawQuery *string
}

// ComputeLayerMockParseQueryResults contains results of the computeLayer.ParseQuery
type ComputeLayerMockParseQueryResults struct {
	c1  entity.Command
	err error
}

// ComputeLayerMockParseQueryOrigins contains origins of expectations of the computeLayer.ParseQuery
type ComputeLayerMockParseQueryExpectationOrigins struct {
	origin         string
	originRawQuery string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmParseQuery *mComputeLayerMockParseQuery) Optional() *mComputeLayerMockParseQuery {
	mmParseQuery.optional = true
	return mmParseQuery
}

// Expect sets up expected params for computeLayer.ParseQuery
func (mmParseQuery *mComputeLayerMockParseQuery) Expect(rawQuery string) *mComputeLayerMockParseQuery {
	if mmParseQuery.mock.funcParseQuery != nil {
		mmParseQuery.mock.t.Fatalf("ComputeLayerMock.ParseQuery mock is already set by Set")
	}

	if mmParseQuery.defaultExpectation == nil {
		mmParseQuery.defaultExpectation = &ComputeLayerMockParseQueryExpectation{}
	}

	if mmParseQuery.defaultExpectation.paramPtrs != nil {
		mmParseQuery.mock.t.Fatalf("ComputeLayerMock.ParseQuery mock is already set by ExpectParams functions")
	}

	mmParseQuery.defaultExpectation.params = &ComputeLayerMockParseQueryParams{rawQuery}
	mmParseQuery.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmParseQuery.expectations {
		if minimock.Equal(e.params, mmParseQuery.defaultExpectation.params) {
			mmParseQuery.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmParseQuery.defaultExpectation.params)
		}
	}

	return mmParseQuery
}

// ExpectRawQueryParam1 sets up expected param rawQuery for computeLayer.ParseQuery
func (mmParseQuery *mComputeLayerMockParseQuery) ExpectRawQueryParam1(rawQuery string) *mComputeLayerMockParseQuery {
	if mmParseQuery.mock.funcParseQuery != nil {
		mmParseQuery.mock.t.Fatalf("ComputeLayerMock.ParseQuery mock is already set by Set")
	}

	if mmParseQuery.defaultExpectation == nil {
		mmParseQuery.defaultExpectation = &ComputeLayerMockParseQueryExpectation{}
	}

	if mmParseQuery.defaultExpectation.params != nil {
		mmParseQuery.mock.t.Fatalf("ComputeLayerMock.ParseQuery mock is already set by Expect")
	}

	if mmParseQuery.defaultExpectation.paramPtrs == nil {
		mmParseQuery.defaultExpectation.paramPtrs = &ComputeLayerMockParseQueryParamPtrs{}
	}
	mmParseQuery.defaultExpectation.paramPtrs.rawQuery = &rawQuery
	mmParseQuery.defaultExpectation.expectationOrigins.originRawQuery = minimock.CallerInfo(1)

	return mmParseQuery
}

// Inspect accepts an inspector function that has same arguments as the computeLayer.ParseQuery
func (mmParseQuery *mComputeLayerMockParseQuery) Inspect(f func(rawQuery string)) *mComputeLayerMockParseQuery {
	if mmParseQuery.mock.inspectFuncParseQuery != nil {
		mmParseQuery.mock.t.Fatalf("Inspect function is already set for ComputeLayerMock.ParseQuery")
	}

	mmParseQuery.mock.inspectFuncParseQuery = f

	return mmParseQuery
}

// Return sets up results that will be returned by computeLayer.ParseQuery
func (mmParseQuery *mComputeLayerMockParseQuery) Return(c1 entity.Command, err error) *ComputeLayerMock {
	if mmParseQuery.mock.funcParseQuery != nil {
		mmParseQuery.mock.t.Fatalf("ComputeLayerMock.ParseQuery mock is already set by Set")
	}

	if mmParseQuery.defaultExpectation == nil {
		mmParseQuery.defaultExpectation = &ComputeLayerMockParseQueryExpectation{mock: mmParseQuery.mock}
	}
	mmParseQuery.defaultExpectation.results = &ComputeLayerMockParseQueryResults{c1, err}
	mmParseQuery.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmParseQuery.mock
}

// Set uses given function f to mock the computeLayer.ParseQuery method
func (mmParseQuery *mComputeLayerMockParseQuery) Set(f func(rawQuery string) (c1 entity.Command, err error)) *ComputeLayerMock {
	if mmParseQuery.defaultExpectation != nil {
		mmParseQuery.mock.t.Fatalf("Default expectation is already set for the computeLayer.ParseQuery method")
	}

	if len(mmParseQuery.expectations) > 0 {
		mmParseQuery.mock.t.Fatalf("Some expectations are already set for the computeLayer.ParseQuery method")
	}

	mmParseQuery.mock.funcParseQuery = f
	mmParseQuery.mock.funcParseQueryOrigin = minimock.CallerInfo(1)
	return mmParseQuery.mock
}

// When sets expectation for the computeLayer.ParseQuery which will trigger the result defined by the following
// Then helper
func (mmParseQuery *mComputeLayerMockParseQuery) When(rawQuery string) *ComputeLayerMockParseQueryExpectation {
	if mmParseQuery.mock.funcParseQuery != nil {
		mmParseQuery.mock.t.Fatalf("ComputeLayerMock.ParseQuery mock is already set by Set")
	}

	expectation := &ComputeLayerMockParseQueryExpectation{
		mock:               mmParseQuery.mock,
		params:             &ComputeLayerMockParseQueryParams{rawQuery},
		expectationOrigins: ComputeLayerMockParseQueryExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmParseQuery.expectations = append(mmParseQuery.expectations, expectation)
	return expectation
}

// Then sets up computeLayer.ParseQuery return parameters for the expectation previously defined by the When method
func (e *ComputeLayerMockParseQueryExpectation) Then(c1 entity.Command, err error) *ComputeLayerMock {
	e.results = &ComputeLayerMockParseQueryResults{c1, err}
	return e.mock
}

// Times sets number of times computeLayer.ParseQuery should be invoked
func (mmParseQuery *mComputeLayerMockParseQuery) Times(n uint64) *mComputeLayerMockParseQuery {
	if n == 0 {
		mmParseQuery.mock.t.Fatalf("Times of ComputeLayerMock.ParseQuery mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmParseQuery.expectedInvocations, n)
	mmParseQuery.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmParseQuery
}

func (mmParseQuery *mComputeLayerMockParseQuery) invocationsDone() bool {
	if len(mmParseQuery.expectations) == 0 && mmParseQuery.defaultExpectation == nil && mmParseQuery.mock.funcParseQuery == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmParseQuery.mock.afterParseQueryCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmParseQuery.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ParseQuery implements mm_database.computeLayer
func (mmParseQuery *ComputeLayerMock) ParseQuery(rawQuery string) (c1 entity.Command, err error) {
	mm_atomic.AddUint64(&mmParseQuery.beforeParseQueryCounter, 1)
	defer mm_atomic.AddUint64(&mmParseQuery.afterParseQueryCounter, 1)

	mmParseQuery.t.Helper()

	if mmParseQuery.inspectFuncParseQuery != nil {
		mmParseQuery.inspectFuncParseQuery(rawQuery)
	}

	mm_params := ComputeLayerMockParseQueryParams{rawQuery}

	// Record call args
	mmParseQuery.ParseQueryMock.mutex.Lock()
	mmParseQuery.ParseQueryMock.callArgs = append(mmParseQuery.ParseQueryMock.callArgs, &mm_params)
	mmParseQuery.ParseQueryMock.mutex.Unlock()

	for _, e := range mmParseQuery.ParseQueryMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.c1, e.results.err
		}
	}

	if mmParseQuery.ParseQueryMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmParseQuery.ParseQueryMock.defaultExpectation.Counter, 1)
		mm_want := mmParseQuery.ParseQueryMock.defaultExpectation.params
		mm_want_ptrs := mmParseQuery.ParseQueryMock.defaultExpectation.paramPtrs

		mm_got := ComputeLayerMockParseQueryParams{rawQuery}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.rawQuery != nil && !minimock.Equal(*mm_want_ptrs.rawQuery, mm_got.rawQuery) {
				mmParseQuery.t.Errorf("ComputeLayerMock.ParseQuery got unexpected parameter rawQuery, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmParseQuery.ParseQueryMock.defaultExpectation.expectationOrigins.originRawQuery, *mm_want_ptrs.rawQuery, mm_got.rawQuery, minimock.Diff(*mm_want_ptrs.rawQuery, mm_got.rawQuery))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmParseQuery.t.Errorf("ComputeLayerMock.ParseQuery got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmParseQuery.ParseQueryMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmParseQuery.ParseQueryMock.defaultExpectation.results
		if mm_results == nil {
			mmParseQuery.t.Fatal("No results are set for the ComputeLayerMock.ParseQuery")
		}
		return (*mm_results).c1, (*mm_results).err
	}
	if mmParseQuery.funcParseQuery != nil {
		return mmParseQuery.funcParseQuery(rawQuery)
	}
	mmParseQuery.t.Fatalf("Unexpected call to ComputeLayerMock.ParseQuery. %v", rawQuery)
	return
}

// ParseQueryAfterCounter returns a count of finished ComputeLayerMock.ParseQuery invocations
func (mmParseQuery *ComputeLayerMock) ParseQueryAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmParseQuery.afterParseQueryCounter)
}

// ParseQueryBeforeCounter returns a count of ComputeLayerMock.ParseQuery invocations
func (mmParseQuery *ComputeLayerMock) ParseQueryBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmParseQuery.beforeParseQueryCounter)
}

// Calls returns a list of arguments used in each call to ComputeLayerMock.ParseQuery.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmParseQuery *mComputeLayerMockParseQuery) Calls() []*ComputeLayerMockParseQueryParams {
	mmParseQuery.mutex.RLock()

	argCopy := make([]*ComputeLayerMockParseQueryParams, len(mmParseQuery.callArgs))
	copy(argCopy, mmParseQuery.callArgs)

	mmParseQuery.mutex.RUnlock()

	return argCopy
}

// MinimockParseQueryDone returns true if the count of the ParseQuery invocations corresponds
// the number of defined expectations
func (m *ComputeLayerMock) MinimockParseQueryDone() bool {
	if m.ParseQueryMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ParseQueryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ParseQueryMock.invocationsDone()
}

// MinimockParseQueryInspect logs each unmet expectation
func (m *ComputeLayerMock) MinimockParseQueryInspect() {
	for _, e := range m.ParseQueryMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ComputeLayerMock.ParseQuery at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterParseQueryCounter := mm_atomic.LoadUint64(&m.afterParseQueryCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ParseQueryMock.defaultExpectation != nil && afterParseQueryCounter < 1 {
		if m.ParseQueryMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ComputeLayerMock.ParseQuery at\n%s", m.ParseQueryMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ComputeLayerMock.ParseQuery at\n%s with params: %#v", m.ParseQueryMock.defaultExpectation.expectationOrigins.origin, *m.ParseQueryMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcParseQuery != nil && afterParseQueryCounter < 1 {
		m.t.Errorf("Expected call to ComputeLayerMock.ParseQuery at\n%s", m.funcParseQueryOrigin)
	}

	if !m.ParseQueryMock.invocationsDone() && afterParseQueryCounter > 0 {
		m.t.Errorf("Expected %d calls to ComputeLayerMock.ParseQuery at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ParseQueryMock.expectedInvocations), m.ParseQueryMock.expectedInvocationsOrigin, afterParseQueryCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ComputeLayerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockParseQueryInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ComputeLayerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ComputeLayerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockParseQueryDone()
}
